### ISSUE TITLE
Option pour cacher les jets et caracs des PNJs

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#104]
Il y aurait de la demande pour une option permettant de ne pas dévoiler aux joueurs les caractéristiques de PNJs lors des attaques et autres jets. Il faudrait juste dire si l'attaque touche (normale, critique, ratée), et le montant total des dégâts, sans qu'on puisse voir le jet de DM.

**Comment by Far2Casual** [comment]
Salut Ulty, je vois ce ticket et je me demande, est-ce que ce n'est pas en partie déjà fait via la gestion de l'option "Jets cachés" sur les feuilles ?

D'ailleurs à ce sujet, je dois bien avouer que le changement qui a été faite sur la gestion des attaques secrètes via l'option en question ne me convient pas vraiment. Les attaques ne sont plus visibles pour les joueurs autres que moi et la cible et c'est pas forcément super agréable. J'envisage du coup de repasser tous mes tokens de PNJs en jets non-cachés.

Mais du coup je me demande : plutôt que de faire les attaques en secret, ne pourrait-on pas se dire plutôt que l'option "Jets cachés" de la feuille aurait le comportement que tu décris dans ce ticket, plutôt que de cacher toute l'attaque à tout le monde ?

**Comment by Ulty** [comment]
Tiens, je suis surpris que quelqu'un qui utilise le script se serve de cette option de la fiche !
Mais tu as raison, c'est une implémentation rapide, ce serait bien mieux comme je l'ai décrit dans ce ticket.

**Comment by Far2Casual** [comment]
Du coup ben à moins que tu voies autre chose, pour moi tu peux clôturer ceci.

**Comment by Ulty** [comment]
Tu as sacrément bien bossé ce week-end ! Merci !
