### ISSUE TITLE
Attaques magiques & PNJ

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#110]
En implémentant Mot de Mort je me suis aperçu que les attaques magiques telles qu'implémentées ne fonctionnait pas bien sur les PNJ qui n'ont pas de valeur d'attaque magique par défaut. Ainsi Geriseb (Anathazerin S5) qui fait un Tueur Fantasmagorique aura un maigre +2 à la touche de son attaque magique. C'est encore plus embêtant en cas de défense face à une attaque magique.

Mais ça me paraît pas si simple que ça à régler, puisque nulle part sur une fiche de PNJ tu ne peux effectivement activer une valeur d'attaque magique ...

**Comment by Ulty** [comment]
Effectivement, il faudra corriger ça. Par défaut, la règle dit d'utiliser le score d'attaque du PNJ. Pour les cas où il y a une attaque magique différenciée, je pense qu'on peut choisir une attaque avec un type 'sortilège'. Je vais regarder ça.

**Comment by Ulty** [comment]
Ça devrait être plus cohérent, maintenant. @Far2Casual : je ne sais pas si tu peux fermer l'issue ? Si oui, tu veux bien le faire après avoir vérifié que ça fonctionnait bien pour toi ?

**Comment by Far2Casual** [comment]
Ouais c'est bien mieux, merci @Ulty.
