### ISSUE TITLE
Fauchage buggé ?

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#111]
J'encode l'issue histoire de pas oublier, mais j'ai l'impression que le "fauchage true" ne fonctionne plus.

**Comment by Ulty** [comment]
@Far2Casual :Je viens de tester, et ça marchait. Tu as vérifié le nom de ton attribut (il peut y avoir une espace à la fin du nom quand on copie-colle depuis la doc) ?

**Comment by Far2Casual** [comment]
Bleh je suis un attardé c'était effectivement le souci. Merci Ulty !
