### ISSUE TITLE
Vague psionique

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#113]
Un de mes persos va reroll un Psionique lvl 6 et on se penche sur Vague Psionique (attaque mentale rang 4). Si je comprends bien la capacité, avec Tempête de Mana et 4 PM supplémentaires en magie puissante, il peut faire 3+CHA attaques avec 7D6+CHA dommages.

Comment implémenter ça au mieux ? 

- Simplement un sort qui fait la dépense de mana, et puis utilisation d'une variante de l'attaque mentale avec --plus [[xD6]] pour les dégâts ?
- Un sort spécial qui fait la dépense de mana, enregistre dans un attribut les bonus temporaires aux dégâts, et réutilisation de l'attaque mentale déjà créée ?
- Il y a moyen de faire une attaque sur X cibles (X étant dynamique puisque c'est 3+CHA) choisies ?

**Comment by Ulty** [comment]
Ça ne va pas forçement résoudre le problème général, mais pour le psionique ,je conseillerais plutôt de ne pas utiliser les règles de tempête de mana. Le profil est bien trop fort. Et en plus il a les avantage (chance, social) d'un fort charisme. Et comme il ne fait pas magie, ça se justifie tout à fait, de ne pas utiliser de tempête de mana.

**Comment by Far2Casual** [comment]
Ne pas utiliser du tout les points de Mana alors ?

**Comment by Ulty** [comment]
Pourquoi pas ne pas utiliser de mana. Surtout que pas mal de capacités de rang 3 ou plus sont déjà limitées par combat ou par jour. J'avais plus dans l'idée d'appeler les points de mana des points de psi et d'utiliser les règles de base, avec soit l'utilisation d'une action d'attaque, soit augmenter les dés de DM en action limitée, ce qui ferait une vague psy à 3d8+CHA, c'est déjà bien. Mais en fait, sans mana, c'est peut-être mieux...

**Comment by Far2Casual** [comment]
Je vais faire ça. Du coup cette capa j'ai pas vraiment besoin d'implémentation, l'attaque mentale de base suffira.
