### ISSUE TITLE
Attaque avec saves & boutons de reroll

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#114]
Quand une attaque qui génère un effet spécial lié à une sauvegarde (ex : l'option d'attaque --pietine) touche et que la cible utilise une option qui va faire en sorte que le script annule l'attaque et la relance (ex : esquive acrobatique), les jets de sauvegarde et donc les effets sont relancés avec. 

Dans le cas précédent, le barde se fait toucher par le piétinement mais réussit sa save, il tente une esquive acrobatique et rate, le script va relancer les jets de sauvegarde et donc le barde a le risque de rater sa save et de se faire piétiner. 

Ce serait cool qu'en plus des jets d'attaque, les jets de sauvegarde soient persistés également.

**Comment by Ulty** [comment]
Tout à fait d'accord, c'est sur ma liste de todo.  Il faut juste décider comment organiser la structure des options pour garder les rolls, sur le modèle de rollsAttack et rollsDmg.

**Comment by Far2Casual** [comment]
Ulty, j'avais pas vu que tu te l'étais assigné. J'ai quasiment fini ...

**Comment by Ulty** [comment]
C'est bon, je n'ai en fait pas eu le temps de commencer (une partie à préparer pour hier soir). Mais pour une prochaine fois, ce serait bien de te mettre en assigned avant de commencer à travailler sur une issue (si tu en as les droits ?). Ça me permettrait de savoir si quelqu'un travaille sur une partie du code, et comme ça j'évite de toucher à cette partie pour réduire les chances de conflits.

**Comment by Far2Casual** [comment]
Malheureusement je ne peux pas m'assigner d'issue. Mais si tu me l'autorises je le fais avec plaisir.

**Comment by Ulty** [comment]
Je vais ré-organiser un peu les structures d'événement.

**Comment by Far2Casual** [comment]
Ok j'attends un peu alors avant de continuer #53 puisque ce que je voulais faire c'était rajouter les boutons chance sur certains autres types d'events.

**Comment by Ulty** [comment]
J'ai fini. Tout est maintenant dans une structure rolls, sauf les dégâts qui sont dans les cibles.

**Comment by Ulty** [comment]
Au fait, j'ai l'impression que cette issue est résolue, non ?

**Comment by Far2Casual** [comment]
J'ai fait les cas que j'ai vu, c'est-à-dire les attaques normales avec Pietinement (en jet opposé), et les jets de sauvegardes effets et etats. Je pense qu'il y a probablement d'autres cas, commes les attaques opposées par exemple. Mais a priori je peux fermer ceci oui.
