### ISSUE TITLE
Attaque de groupe : +5 / créature supplémentaire ?

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#115]
Suggestion pour les gestions de haute DEF, et pour les scénars "du milieu" de Anathazerïn (5/6/7/8) où des PJs puissants sont encore fréquemment confrontés à des pécores NC1/2 (orcs) : implémenter la règle d'attaque en groupe de Vengeance et la fusionner à celle du compagnon : 
- +5 à la touche par créature supplémentaire (au lieu de +2 ce qui est très insuffisant)
- dommages x2 si touche > DEF + 5

**Comment by Ulty** [comment]
Heu, c'est déjà implémenté tout ça. Tu n'as pas remarqué le bouton 'options' au début des cadres des actions du tour ?

**Comment by Ulty** [comment]
Pardon, j'avais pas bien compris le message d'origine.

**Comment by Ulty** [comment]
Du coup, je ne suis pas sûr que la combinaison des deux règles soit équilibrée. Je vais étudier ça, mais le mieux serait peut-être de créer une option de jeu, non ? Du genre, quel bonus donner par adversaire au-delà du premier en cas d'attaque de groupe, par défaut +2 ?

**Comment by Ulty** [comment]
Tu as des PJs avec combien en DEF, et des PNJs ont combien en attaque ?

**Comment by Far2Casual** [comment]
La DEF moyenne de mon group de PJs lvl 6 c'est 20. Un orc ça a +2 en attaque.
L'idée c'est de ne jamais faire d'attaques à plus de 3 ou 4 créatures de toute façon.

**Comment by Far2Casual** [comment]
Autre possibilité : fusionner à la règle des sbires du compagnon, càd ne multiplier les dégâts que si on dépasse de 10 la DEF.
Ainsi, 4 Orcs frappent à +17, mais ne doublent leurs (maigres) dégâts que s'ils font 13+.

**Comment by Ulty** [comment]
> La DEF moyenne de mon group de PJs lvl 6 c'est 20. Un orc ça a +2 en attaque.
> L'idée c'est de ne jamais faire d'attaques à plus de 3 ou 4 créatures de toute façon.

Du coup, à 4, ils font 2 fois plus de dégâts en moyenne avec cette option de groupe qu'en faisant les 4 attaques. Avec un bonus de +3, ils font juste environ 25% de dégâts de plus. Qu'est-ce qui te semble le plus raisonnable ? (Avec +2, c'est vraiment pas assez, ça fait même moins de dégâts en moyenne !)

**Comment by Far2Casual** [comment]
Dans Vengeance c'est limité à +10 avec 3 créatures. N'est-ce pas une option ?

**Comment by Far2Casual** [comment]
Voilà Ulti, j'en ai fait une option de règle. Par défaut ça implémente la version du Compagnon (+2 par créature, x2 si jet>DEF+5). Mais on peut changer les deux valeurs (le bonus et le niveau de crit, et il est même possible de retirer complètement l'effet sans critique).
Personnellement je pense me diriger vers une version avec un gros bonus par créature mais sans effet de critique, afin d'avoir un effet "d'usure" sur des personnages débordés, sans l'effet "explosion".

**Comment by Ulty** [comment]
Oui, ça se tient. Merci pour l'implémentation !
