### ISSUE TITLE
undoEvent() dans le cadre d'un reroll d'attaque

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#119]
undoEvent() retire bien les états et effets sur les tokens, mais le problème c'est que si l'état en question a été donné sur une attaque, j'ai l'impression que l'était n'est pas retiré sur la "copie" du token qui est dans la sérialisation de l'event. Du coup lors du reroll de l'attaque, le token a toujours l'état ce qui peut mener à des trucs bizarres.

Exemple : 
1. un ours-hibou attaque un barde avec une charge avec piétinement, touche, et le barde rate le jet opposé de force et est renversé.
![image](https://user-images.githubusercontent.com/63196064/94480020-f2e9c300-01d5-11eb-8f60-2838a2c149a0.png)
2. A ce moment-là le barde tente une esquive acrobatique. On voit juste en-dessous dans le chat qu'undoEvent est appelé et restaure l'état renversé du token.
![image](https://user-images.githubusercontent.com/63196064/94480095-16147280-01d6-11eb-8ad3-58a409b439ff.png)
3. Dans le reroll de l'attaque pourtant, le pauvre barde est considéré comme renversé et subit donc -5 à son jet de DEX.
![image](https://user-images.githubusercontent.com/63196064/94480183-38a68b80-01d6-11eb-92b2-308f898a3353.png)

**Comment by Ulty** [comment]
C'est une question d'ordre des actions, pas de copie des tokens : l'esquive acrobatique fait d'abord le jet d'attaque à distance du barde avant de faire le undo de l'attaque qu'il esquive. Je vais corriger ça.

**Comment by Ulty** [comment]
Je te laisse vérifier et fermer l'issue si ça fonctionne.

**Comment by Far2Casual** [comment]
Niquel, merci !
