### ISSUE TITLE
!cof-init

### ISSUE THREAD

**Issue by waibcam** [Ulty/COFantasy#12]
J'ai remarqué un "bug ? (ou pas)" lors d'un !cof-init :
La fonction _setActiveToken_ n'est pas appelé durant l'init. Du coup, le premier joueur n'a pas de drapeau (et mon script n'est pas appelé).
Il faut passer au joueur suivant pour que le drapeau apparaisse.

**Comment by Ulty** [comment]
Non, je n'ai pas vu ça. Quand je fais !cof-init sur un groupe de tokens, je vois bien le drapeau pour le premier joueur.
D'ailleurs setActiveToken est appelé dans setTurnOrder qui est appelé à la fin de la fonction initiative.
Tu aurais un exemple reproductible pour le bug ?

**Comment by waibcam** [comment]
Je me suis arraché les cheveux hier soir avec ce trucs.
A priori, sans que je comprenne pourquoi, cela vient de deux de mes personnages qui s'appelle respectivement "Maximus" et "Aegon".

Si je laisse la feuille de perso et le nom du token avec "Maximus" et "Aegon" ca ne fonctionne pas.
Par contre, si je rajoute un tréma sur le "u" de Maximus et un sur le "e" d'Aegon (donc "Maximüs" et "Aëgon"), là tout va bien (WTF !?).

Pour la rigolade, si j'appelle le perso et le token "Max" au lieu de "Maximus" et bien ça fonctionne aussi...

Bref, j'insiste pas, je mets des trémas et ça roule ma poule.

**Comment by Ulty** [comment]
C'est pas normal, tout ça. J'ai l'impression que pour que ça fonctionne, il faut que le nom du token soit différent du nom du personnage. Je vais essayer de regarder ça d'un peu plus près. Tu ne pourrais pas reproduire le truc, par exemple en copiant le jeu, ou alors avec un jeu vide et en important juste un perso qui pose problème ?

**Comment by Ulty** [comment]
Non, je n'arrive pas à reproduire ça chez moi.

**Comment by waibcam** [comment]
Je tâcher de trouver un moyen de reproduire.

Sinon, j'ai trouvé un truc qui n'est pas lié à mon souci de nom de perso mais qui a dû me faire tourner en bourrique indirectement.

Tu es hors combat, tu choisi deux personnages (alliés par exemple) en les sectionnant tous les deux et tu !cof-init : là tout va bien. Tu !cof-hors-combat  et tu mets à nouveau les même perso en !cof-init.
Là, je n'ai plus le drapeau au départ.

**Comment by Ulty** [comment]
Ce bug là, je peux le reproduire ! Je vais essayer de corriger ça.

**Comment by waibcam** [comment]
AH ! ! ! ! ! ! !
Je crois avoir trouvé d'où vient le bug avec le nom !

En fait, lorsqu'un joueur et un personnage ont le même nom, la commande /w envoie uniquement au joueur la commande plutôt qu'à l'ensemble des joueurs qui contrôle le personnage (controlledby).

Dans mon cas, les deux joueurs en question doivent avoir paramétré leurs "Display Name" exactement comme leur personnage (ce qui est normal en somme). Donc ils recevaient bien les messages mais je ne pouvais pas les voir, même en m'ajoutant dans le "controlledby"...

Bref, tout va bien alors !

Il ne reste plus que le petit bug avec !cof-init

**Comment by Ulty** [comment]
Bravo pour avoir trouvé ! Il était tordu, celui-là !

**Comment by waibcam** [comment]
Je devenais fou :D Mais trop content d'avoir trouvé !

**Comment by Ulty** [comment]
Ça devrait être corrigé, maintenant.

**Comment by waibcam** [comment]
génial ! Merci :)
