### ISSUE TITLE
Support de "Riposte" (Guerrier/Maître d'armes r5)

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#120]
Je vois dans la doc "pas de support particulier" pour la riposte du Guerrier. Or il me semble qu'il y a déjà des systèmes d'attaque opportunité, comme pour Seul contre Tous du Chevalier par exemple. 

Une raison particulière que je ne comprends pas pour laquelle il n'y a pas de support ? 
Ca te va si je fais ça (j'ai un guerrier qui l'utilise) ?

**Comment by Ulty** [comment]
Effectivement, on doit pouvoir le faire. En relisant la chose, je me demande si j'avais bien compris le Seul contre tous du chevalier. Je crois que je n'ai pas pris en compte le fait que ça nécessite une action limitée de la part du chevalier. Si tu veux corriger ça, je t'en prie :).

**Comment by Far2Casual** [comment]
Effectivement, il faut en faire une action. Ok je prends tout ça.

**Comment by Far2Casual** [comment]
Je vais créer une autre issue pour la partie Chevalier, et probablement encore une autre pour la gestion de la macro "#AttaquesRiposte#" qui a un peu mal avec les nouvelles attaques & fiches.

**Comment by Ulty** [comment]
Je vais accepter le pull, mais changer un peu la facon dont ça fonctionne, pour ne pas avoir à gérer les initiatives bizarrements : un attribut riposteGuerrier, de valeur courante et maximale 1 (nombre maximum de ripostes dans le tour).
