### ISSUE TITLE
Implémentation 2.0 des esquives/parade/rune de protection

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#128]
Bon je crée ce petit sujet pour discuter de l'implémentation potentielle des éléments repris ici : https://www.black-book-editions.fr/forums.php?topic_id=18110

En discutant avec un autre MJ de CoF, il me disait qu'il avait fait un ruling similaire sur la capa de prêtre qui permet de faire réussir ou échouer un jet automatiquement, ou encore sur l'esquive du voleur ; ils devaient choisir d'utiliser ou non leur capacité en fonction d'une simple annonce "réussite ou pas" (sans information de critique) **avant** que les dommages soient annoncés.

Du coup on pourrait faire un affichage spécial temporaire si on attaque un joueur disposant d'une capacité permettant d'annuler une attaque. Cet affichage indique simplement si l'attaque a échoué ou pas, et si elle touche, deux boutons "utiliser la capacité" ou "prendre le coup", et l'attaque est réalisée avec ou sans la capacité en question.

Une autre suggestion ?

**Comment by Far2Casual** [comment]
J'ai énormément progressé, la base fonctionne déjà (esquive acrobatique, rune de protection). 
Je repasse dans toutes les options implémentées qui permettent d'esquiver une attaque et je pourrai push demain. 
C'est vraiment mieux !

**Comment by Ulty** [comment]
Excellente idée, et ça devrait avoir un affichage plus sympa. Il faut juste faire attention aux capacités pour lesquelles il est explicitement précisé que le joueur prend la décision après avoir pris connaissance des dommages, comme le **Petit veinard** des halfelins.

**Comment by Far2Casual** [comment]
Je te montre un peu ce que ça donne : j'ai pris un Ours-hibou qui attaque un Barde avec Esquive Acrobatique et une Rune de Protection. Pour info j'ai rajouté un état avec save sur son attaque pour ça aussi.

1. L'ours-Hibou touche : 
![image](https://user-images.githubusercontent.com/63196064/94906204-59a10200-049e-11eb-8e31-7372d5d7cf78.png)

2. Le Barde utilise son Esquive Acrobatique
![image](https://user-images.githubusercontent.com/63196064/94906257-6f162c00-049e-11eb-933f-7174551f4e4c.png)

3a. Le Barde décide de ne pas utiliser sa Rune de Protection et appuie sur "Continuer"
![image](https://user-images.githubusercontent.com/63196064/94906312-8bb26400-049e-11eb-84d8-13130fdbe91a.png)

3b (autre exemple). Le Barde utilise sa Rune de Protection, l'attaque est faite sans dommages mais les états sont calculés
![image](https://user-images.githubusercontent.com/63196064/94906371-a684d880-049e-11eb-919c-19436335bff4.png)

Qu'en penses-tu ?

**Comment by Ulty** [comment]
Oui, ça rend bien ! Si possible, je mettrais le message **Attaque : Touche !** en premier.  Et même, les messages d'explication avant les boutons pour éviter l'attaque, ça me semblerait plus logique.

**Comment by Far2Casual** [comment]
Nouvelle version : 

1. Charge de l'ours qui touche : 
![image](https://user-images.githubusercontent.com/63196064/94986999-8bc86780-0563-11eb-8f8f-7f435209a7db.png)

2. Tentative ratée d'esquive acrobatique : 
![image](https://user-images.githubusercontent.com/63196064/94987023-a7cc0900-0563-11eb-9215-8ab46a8bcc16.png)

3. Rune de Protection : 
![image](https://user-images.githubusercontent.com/63196064/94987047-bd413300-0563-11eb-9982-4390c81bea37.png)

**Comment by Far2Casual** [comment]
Maintenant je tente de gérer les attaques de zone, mais là c'est forcément plus compliqué, et surtout moins ultime. En effet à cause de valeurs de DEF potentiellement différentes, il est évidemment plus compliqué d'afficher les boutons sur une attaque qui peut toucher un joueur et pas l'autre ; forcément l'information sur le jet total d'attaque est bien plus visible ...

**Comment by Far2Casual** [comment]
Matte-moi ça !

1. Annita fait un éclair sur deux persos : 
![image](https://user-images.githubusercontent.com/63196064/94989460-46ad3100-0575-11eb-806e-f05ab94bc65a.png)

2. Le Barde utilise son Esquive Acrobatique et réussit : 
![image](https://user-images.githubusercontent.com/63196064/94989472-617fa580-0575-11eb-80c7-628429deb0a0.png)

3. Le Guerrier décide de ne pas utiliser sa Rune de Protection : 
![image](https://user-images.githubusercontent.com/63196064/94989483-7ceab080-0575-11eb-99cf-f2175bf1687a.png)

Ca prend forme !
Next : 
1. Voir si je peux un peu mieux trier les explication (dans le screenshot 3 ci-dessus, j'aimerais que l'info sur l'esquive de Gerulf se mettre au niveau de l'attaque sur Gerulf.
2. Je dois réécrire la rune de protection pour les attaques de zone
3. Tester une fois sur toutes les capas que j'ai appelé "preDmg" dans le code

**Comment by Ulty** [comment]
Ça progresse bien !

**Comment by Far2Casual** [comment]
J'ai quasiment fini mais j'ai une question : c'est quoi "parade magistrale" ? Je n'en trouve de trace nulle part : livre de base, compagnon, documentation. Et aucune génération du bouton dans le script. 
Par contre il y a une méthode pour gérer ça dans le code. Quid ?

**Comment by Ulty** [comment]
C'est une capacité pour un profil de duelliste que j'ai inventé (enfin, basé sur du barde/voleur). Un jour, il faudra que je le mette sur le forum, pour avoir d'autres avis. Bref, c'est une capacité très similaire à l'esquive acrobatique, mais plus efficace au contact, et qui peut bénéficier des effets d'une feinte. Et c'est bien utilisé dans le script.

**Comment by Far2Casual** [comment]
Ok je l'inclus. Question suivante ...
Dans le refactoring, les capacités suivantes sont passées en mode "à décider avant le jet de dommages" : 
- Encaisser un coup
- Résistance à la Magie Barbare
- Esquive Acrobatique
- Absorber un coup / un sort
- Parade Magistrale

Pour "Ignorer la Douleur" du Chevalier, je fais quoi : avant ou après les dommages ?

**Comment by Ulty** [comment]
Je pense que pour ignorer la douleur, je ferais après les dommages. Qu'est-ce que tu en penses ?

**Comment by Far2Casual** [comment]
Je pense qu'on est d'accord.

**Comment by Ulty** [comment]
Je suis en train de regarder un peu le code. Il me semble que les options d'évitement de l'attaque ne devraient  être utiles que si l'attaque fait des DM, non ? Si tu es d'accord, je vais garder tout ça pas un 

if (!options.pasDeDmg)

**Comment by Far2Casual** [comment]
Oui est non, pour certaines sur certaines attaques il pourrait y avoir un côté débilitant, que l'on pourrait avoir envie d'esquiver ?

**Comment by Ulty** [comment]
Pardon, j'étais sur l'esquive acrobatique, qui ne dit pas qu'on ne subit pas les effets mais que le barde ne prend pas de DM. mais ça doit juste être la capacité qui est mal écrite.
