### ISSUE TITLE
Les RD fixes ne sont plus appliquées

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#136]
Je report ça vite fait, déjà remarqué ça ce jeudi.

![image](https://user-images.githubusercontent.com/63196064/97114239-b08da600-16ef-11eb-8422-4e3de0653ef4.png)
![image](https://user-images.githubusercontent.com/63196064/97114246-b97e7780-16ef-11eb-9870-5012a1eacd5c.png)

**Comment by Ulty** [comment]
Je viens de faire un test, et au moins sur ce test, la RD fixe est prise en compte.

**Comment by Far2Casual** [comment]
Pourtant je vois le souci. Voici le code qui me pose souci :
`var attrRD = 'RDS';
    if (persoEstPNJ(perso)) {
      attrRD = 'pnj_rd';
    }`

Or quand je regarde la fiche de mon Géant des Collines, il n'a pas d'attribut pnj_rd, seulement un RDS.
![image](https://user-images.githubusercontent.com/63196064/97146522-47964480-1768-11eb-995b-66b32423fa49.png)

**Comment by Ulty** [comment]
Effectivement, j'avais utilisé une ancienne version de géant des collines (avec transmogrifier). C'est corrigé.

**Comment by Far2Casual** [comment]
Top, merci. J'osais pas trop le faire moi-même parce que j'ai vu que tu étais occupé à modifier des trucs dans les fiches, et je ne voulais pas mettre le brun.
