### ISSUE TITLE
Toiles (Drows)

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#137]
Je vois que tu as récemment fait quelque chose pour la capacité "Toiles" des Elfes Noirs. En testant le combat des grottes je me suis dit que c'était vachement OP, mais j'ai compris pourquoi : dans la capa, tu as "immobilisés" les persos (D12 à tous les jets, pas de déplacement) alors qu'ils ne sont qu'"entravés" selon la description du sort (-2 Att, -2 DEF, pas de déplacement).

La différence est énorme car les persos Immobilisés ont aussi un D12 au jet de FOR pour se libérer du coup, ce qui rend le sort particulièrement bourrin. Ok pour toi si je mets un nouvel effet "entravé" à la place ?

**Comment by Ulty** [comment]
Hmm, je dois dire que tu m'as un peu perdu là. Tu parles bien de faire `!cof-effet-temp toiles` ? Si oui, ça ne met pas immobilisé (même si ça devrait empêcher de bouger, je vais rajouter ça, tiens). Je vais faire l'essai en jeu, mais en regardant le code, je me demande bien comment ça peut donner d12 à tous les jets...

**Comment by Ulty** [comment]
Je viens de tester, et je vois bien juste l'effet "entravé", avec -2 à l'attaque, et utilisation du d20.

**Comment by Far2Casual** [comment]
Alors je comprends pas ... 
![image](https://user-images.githubusercontent.com/63196064/97436829-e8c8fa80-1922-11eb-809e-e3861d9bed64.png)

**Comment by Far2Casual** [comment]
Je suis con en fait, j'ai codé l'attaque sans utiliser TOiles ... Désolé de prendre ton temps pour des bêtises comme ça >:(
