### ISSUE TITLE
Encaisser sur Riposte

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#138]
J'ai trouvé un bug un peu anecdotique, mais bon voilà : si un Chevalier encaisse une attaque de Riposte de Guerrier, le script plante. La raison : en cliquant sur "Encaisser un coup", l'attaque se refait. Or sur une riposte, il y a dans les options "--decrAttribute X", et lors de l'appel à limiteRessources, ça plante.

Question : que vaut-il mieux ?

1. Dans "resoudreAttaque", ne pas appeler limiteRessources si options.redo = true ?
2. Retirer l'option "decrAttribute" au moment où on refait l'attaque après avoir appuyé sur "Encaisser le Coup" (fix potentiellement à appliquer à de nombreuses capacités)

**Comment by Ulty** [comment]
Pas évident. Mais je ne comprends pas pourquoi la limiteRessources plante. Je vais regarder ça.

**Comment by Far2Casual** [comment]
En fait il n'y a pas d'Undo dans "doEncaisser", du coup c'est même incorrect de laisser le decrAttribute, car ça voudrait dire qu'on le ferait descendre deux fois.

**Comment by Ulty** [comment]
Je n'avais pas regardé ça en détail, mais effectivement tu as enlevé le undo avec les esquives 2.0. Je ne vais pas avoir le temps de regarder ça avant la semaine prochaine. Comme tu l'as dit, c'est heureusement un cas peu fréquent.

**Comment by Far2Casual** [comment]
Quand je suis repassé dans tout ce système et toutes les réactions du genre, c'était pas forcément toujours clair car certains l'avaient et d'autres non. Après, je me suis dit que de considérer les deux morceaux comme deux events différents n'était pas déconnant. Mais ce n'est peut-être pas une bonne idée ...
Je te laisse la main sur ce point, c'est effectivement peu problématique.

**Comment by Ulty** [comment]
Je pense que tu as eu raison, ça me semble bien mieux de ne pas faire de undo, mais de considérer l'action comme en attente.

**Comment by Far2Casual** [comment]
En fait, le problème est un peu plus gros que ce que je pensais, car le bug en question va se poser à chaque fois qu'une "ressource" est utilisée par une attaque... comme par exemple la Mana.

Exemple supplémentaire : un Magicien lance Flèche Enflammée pour 1 PM sur un mec avec une Rune de Protection, le Magicien va déjà utiliser son PM lorsque l'affichage intermédiaire est proposé au Guerrier pour l'utilisation ou non de la Rune. Quel que soit le bouton sur lequel on appuie ("Rune" ou "Continuer"), l'attaque va se faire à nouveau, y compris la dépense de PM.

Pour moi le bon fix c'est de ne pas appeler `limiteRessources` dans `resoudreAttaque` si `options.redo=true`. J'ai le fix en local, ça semble être bon.

**Comment by Ulty** [comment]
En fait, je pense couper la fonction d'attaque, histoire de vraiment continuer, sans besoin de tout refaire.

**Comment by Far2Casual** [comment]
Ne faut-il pas appliquer alors la même logique aux autres options "preDmg", telles que Esquive Acrobatique, Rune de Protection, et autres ?

**Comment by Ulty** [comment]
Si bien sûr. J'ai commencé, mais j'ai une semaine bien chargée. Je continue ça dès que j'ai le temps.

**Comment by Far2Casual** [comment]
Impec Ulti, merci.

**Comment by Ulty** [comment]
J'ai mis à jour, mais malheureusement sans le temps de tester, la résistance à la magie et la rune de protection. Si tu as le temps, ça pourrait m'aider que tu testes un peu.

Pour la rune de protection, si on lit strictement la capacité, elle ne permet d'ignorer que les dommages. Qu'est-ce que tu en penses, si on change le script pour que les DMs soient 0, mais que l'attaque touche quand même (et donc puisse renverser, affaiblir, etc...) ?

**Comment by Ulty** [comment]
En revanche, pas sûr de trouver du temps pour continuer à avancer là-dessus ce week-end.

**Comment by Far2Casual** [comment]
Salut Ulti, dans mon implem de base en effet, la Rune de Protection ne protégeait que des dommages, tout le reste était appliqué (etats, poison, etc). Je veux bien reprendre le truc ce week-end, il te reste quoi ?

**Comment by Ulty** [comment]
Ha, oui, tu as raison pour les runes de protection. J'ai corrigé.

**Comment by Far2Casual** [comment]
Bon après mes tests tout ça fonctionne assez bien, j'ai une légère correction pour les Runes de Protection à sortir d'un if(!auto), sinon ça marche assez bien.

**Comment by Ulty** [comment]
Merci d'avoir testé !

**Comment by Ulty** [comment]
Je pense avoir fini avec cette issue. Si tout marche bien pour toi, tu peux fermer.
