### ISSUE TITLE
Réorganisation du menu des options

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#140]
Discuté brièvement dans #99 
Et je voudrais bientôt rajouter une option pour activer la Mana de COTA.

Je propose de créer des catégories dans la partie règles des options. Actuellement je vois ça comme ça : 
- Dommages
-- Blessures graves
-- DM Minimum
-- Crit élémentaire
- Haute DEF
-- Usure DEF
-- Générer options attaques
-- Valeur Bonus Attaque Groupe
-- Valeur Bonus Crit en Groupe
- Initiative
-- Initiative variable
-- Initiative variable individuelle
- Mana
-- Mana Totale
-- Mana Elixirs
- Divers
-- Forme d'arbre
-- Interchangeable
-- Poudre Dé Explosif

**Comment by Ulty** [comment]
Oui, ça me semble bien.

**Comment by Ulty** [comment]
Au fait, il y a toujours besoin de générer les options d'attaque ? Maintenant que tout est dans la liste d'actions ?

**Comment by Far2Casual** [comment]
Tu as raison je vais supprimer ça. C'est l'option que j'ai rajouté et depuis que t'as intégré ça à la liste d'actions, moi-même je ne l'utilise plus.

**Comment by Ulty** [comment]
J'attend ta suppression avant d'intégrer le PR. Comme ça, ce sera plus propre pour le passage à 2.14.
