### ISSUE TITLE
Infos de durée des sorts

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#144]
De nombreux sorts (offensifs et défensifs) ont une durée aléatoire (Sous Tension, Hâte, Rayon affaiblissant, etc). Quand ils lancent ces sorts, les joueurs n'ont aucune visibilité directe sur le résultat de ce jet, malgré que ce soit normalement eux qui réalisent ce jet en partie réelle.

Ok pour que je fasse en sorte que l'info de durée des effetsTemp apparaisse lors du lancement du sort, quand c'est approprié ?

**Comment by Ulty** [comment]
Non, pas vraiment d'accord. Sur table, je fais toujours un jet caché pour la durée des sorts. Je ne vois aucune raison pour que le magicien la connaisse à l'avance quand elle est aléatoire.

**Comment by Far2Casual** [comment]
Tiens, intéressant. Je n'avais jamais vraiment envisagé la chose ... 
Mais tu fais aussi les dégâts aussi en secret alors ? Sinon, pourquoi les dégâts en "public" mais la durée "en privé" ? Je conçois l'intérêt de la chose, mais rien dans les règles ne me permet vraiment de dire à mon joueur qu'il n'a pas accès à l'information.

Aurais-tu une objection à ce que j'en fasse une option éventuellement ?

**Comment by Far2Casual** [comment]
Aucune offense, t'inquiète.

OK, j'envisagerai peut-être d'implémenter une option pour ça alors.
