### ISSUE TITLE
--etat etourdi carac seuil ne fonctionne pas

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#147]
Je note ça ici pour me rappeler de ça, car c'est potentiellement la seule chose qui empêche d'implémenter complètement la voie du colosse rang 3 (à l'exception de la projection mais qui peut facilement être réglée à la main).

Le problème c'est que comme le joueur est étourdi, il n'a pas d'action à son tour et ne se voit donc pas proposer le bouton pour sortir de l'état étourdi.

**Comment by Ulty** [comment]
Pourquoi tu n'utilises pas `--etat etourdi --save carac seuil` ?

**Comment by Far2Casual** [comment]
Parce que normalement le joueur a droit à un test CON 15 tous les tours par la suite pour se sortir de l'état.

**Comment by Ulty** [comment]
Ah, oui ,c'est vrai. Les saves par tours ne sont implémentés que pour les effets temporaires. Mais du coup, tu peux juste utiliser `--effet etourdiTemp 100 carac seuil`, et voilà.

**Comment by Far2Casual** [comment]
Ben non même souci ; comme il est étourdi, il est sorti du Turn Order. Du coup il n'a plus d'initiative, ne reçoit jamais sa liste d'action à son tour, et n'a donc jamais le bouton permettant de faire le jet.

C'est spécifique à l'état étourdi et c'est lié au fait que le joueur sort du Turn Order.

**Comment by Ulty** [comment]
Le fait d'être sorti du tun-order ne signifie pas que le temps s'arrête pour les effets temporaires du personnage.
En revanche, j'ai du désactiver certaines actions pour les personnages qui ne peuvent agir. Je devrais sûrement faire un cas particulier pour les tests de constitution, qui ne demandent en fait aucune action consciente.

**Comment by Ulty** [comment]
Après avoir regardé un peu le code, je ne suis plus si sûr de mon explication : en fait je n'enlève le save que pour les personnages morts. Il va falloir que je creuse ça...

**Comment by Far2Casual** [comment]
Je suis dessus, j'ai bientôt la solution. Comme je pense l'ennui principal vient bien du fait que le perso qui reçoit étourdi est retiré du turn order et ne reçoit jamais sa liste d'action. Je vais implémenter un système qui fait que s'il a droit à une save pour sortir d'un des états qui le rend inactif, il n'est pas sorti du turn order et reçoit une liste d'actions qui se résumé à ses saves.
