### ISSUE TITLE
bug --target @{target|Target2|token_id} et --if --endif

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#148]
Je note aussi ça car je tombe dessus au milieu d'autres tests, et le bug est tellement bizarre que je comprends pas sans aller plus loin, mais suis occupé sur autre chose.

`--target @{target|Target2|token_id}` est utilisé pour Balayage (Voie du Colosse Rang 2). Seul, ça fonctionne bien.

Après je rajoute `--if deAttaque 15 --plus 3d6 --endif` pour implémenter en partie Projection (Voie du Colosse Rang 3), et là ça bug de manière très bizarre. Si on sélectionne deux fois le même token pour l'attaque, ça marche. Si par contre on cible deux tokens différents, alors il ne se passe juste rien. Pas de message d'erreur, pas d'attaque, le script n'est pas planté ... il ne se passe juste rien du tout. Si on retire la partie --if, ça marche à nouveau.

**Comment by Ulty** [comment]
Très étrange, oui !
