### ISSUE TITLE
Sommaire de l'aide impossible à scroller

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#15]
Il ne semble pas possible de faire défiler le sommaire, ce qui fait que si tout ne tient pas sur une page, une partie est inaccessible.

**Comment by waibcam** [comment]
Oh la la, je viens juste de voir cette demande @Ulty 

Je m'occupe de ça dès que je peux !

**Comment by waibcam** [comment]
j'ai fais ce que j'ai pu pur améliorer.
En gros, le menu en "fix" ne peut pas être scrollable alors j'ai fais en sorte qu'il soit juste un peu moins grand.

**Comment by Ulty** [comment]
En utilisation normale, c'est tout à fait suffisant. Merci.
