### ISSUE TITLE
Bug utilisation PC sur Attaque de Riposte (Guerrier)

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#150]
Provoque une erreur

**Comment by Far2Casual** [comment]
Bon alors @Ulty celui-là j'aimerais un peu ton avis.

Grosso modo j'ai l'impression que dans decrAttribute on met normalement directement un objet reçu de l'API roll20, d'où l'utilisation de la fonction .get(). Juste ?

Du coup j'ai l'impression qu'en fait le souci vient que quand on utilise un PC et qu'on refait l'attaque avec les options sauvées dans l'évènement, dans decrAttribute on a plus un objet natif de l'API mais un simple objet, d'où le message d'erreur : 
`"TypeError: attr.get is not a function"`

C'est juste ? Mais qu'est-ce qui est mieux ? Refactoriser limiteRessources de manière à ne pas utiliser un objet roll20, ou bien dans chanceCombat recalculer complètement decrAttribute ?

**Comment by Ulty** [comment]
J'ai déjà eu ce genre de problème. Ça venait à chaque fois que je voulais faire un clone d'une variable pour ne pas modifier la variable de départ. Pour faire ça proprement, il faut traiter les objets Roll20 différemment. Je vais corriger ça.
