### ISSUE TITLE
Evènements en double avec le même ID

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#156]
En faisant des tests pour continuer #53, je me suis aperçu que certains évènements n'étaient pas correctement enregistrés dans l'historique.

Notamment pour !cof-effet-temp et nextTurn (appelé quand on utilise le Turn Order), je remarque qu'on a souvent l'évènement en double dans l'historique, avec le même ID. Généralement parce que je retrouve plusieurs occurences de "addEvent()".

Ca pose un réel souci parce que du coup les ID des events ne sont pas cohérents entre le milieu et la fin du code, et ça bloque l'implémentation des undo/redo.

**Comment by Ulty** [comment]
C'est très bizarre. Normalement, la seule façon dans le code d'ajouter un evt à la liste est avec la fonction `addEvent`, qui assure une numérotation unique, non ?

**Comment by Far2Casual** [comment]
Je peux t'illustrer ça avec la fin de nextTurnOfActive() parce que c'est avec ça que j'ai joué. Voici la toute fin de la méthode 👍 
![image](https://user-images.githubusercontent.com/63196064/98691209-14f66980-236e-11eb-9b24-e017e5b099fe.png)

La première partie c'est la fin d'une boucle où est notamment traité les sauvegardes à faire au tour du joueur. Tu y vois un `count-- et un addEvent`. Et à la toute fin de nextTurnOfActive, il y a un autre `addEvent`.

Perso je comprends pas trop ces "count--" et ces addEvent sachant qu'à la fin de la méthode à peu près quoiqu'il se passe, on a un autre addEvent. Quand j'ai fait des tests avec le code tel quel, j'avais deux vois un event "Tour Suivant" avec le même ID du coup. Quand je supprimais la partie count-- et addEvent à l'intérieur de la boucle, je n'avais alors qu'un seul event avec le bon ID.

Je n'ai pas creusé plus loin parce que je ne comprenais pas trop l'idée et je me suis dit que je t'en parlerais. J'ai remarqué exactement la même chose sur le traitement de !cof-effet-temp.

**Comment by Ulty** [comment]
Je vois le problème, effectivement, c'est le même evt qui est ajouté 2 fois, il est donc en double, avec le même numéro dans la liste. Je vais regarder ça.

**Comment by Far2Casual** [comment]
Merci. Pour info, voici ce que ça donne dans l'historique si tu fais une attaque qui a un effet EtourdiTemp, et puis tu fais "next turn" qui tombe sur le perso étourdi : 
![image](https://user-images.githubusercontent.com/63196064/98692789-cd70dd00-236f-11eb-82c0-abeac2531701.png)

**Comment by Ulty** [comment]
Est-ce que ça va mieux avec le dernier commit ?

**Comment by Far2Casual** [comment]
J'ai testé vite fait sur nextTurn et oui c'est beaucoup mieux !

**Comment by Far2Casual** [comment]
Je me permets de réouvrir, plutôt que de recréer un ticket.
J'ai vu dans le code la "protection" anti double évènement, pour info dans ma séance hier, grâce à ça le script a déteté des tentatives de double ajout lors de l'utilisation de !cof-nouveau-jour également : 
![image](https://user-images.githubusercontent.com/63196064/98922540-dd550200-24d2-11eb-987a-ee575652939f.png)

**Comment by Ulty** [comment]
Tu fais bien de rouvrir le ticket. J'avais mis cette protection justement pour être sûr que ça ne se reproduise pas. Normalement, le code permet d'éviter la duplication et tout devrait fonctionner correctement, mais j'aimerais quand même bien corriger le script...

**Comment by Ulty** [comment]
J'ai changé un peu la façon d'insérer les événements dans l'historique. Comme on fait de toutes façon des modifications d'événements en place, ça ne rimait à rien d'attendre le dernier moment pour les mettre dans l'historique.

**Comment by Far2Casual** [comment]
C'est beaucoup mieux et ça me paraît beaucoup plus logique et facile à utiliser.
Du coup je vois comment faire si je rencontre encore le souci, comme par exemple à l'instant pour !cof-dmg. Merci pour l'aide.
