### ISSUE TITLE
Echange de consommables & fiche

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#157]
J'ai l'impression que si des gens s'échangent des consommables, ils ne sont pas repris sur la fiche du destinataire. Possible ?

**Comment by Ulty** [comment]
Ça ne devrait pas être le cas entre 2 PJs. En revanche, je n'ai pas encore ajouté l'utilisation de la fiche pour les PNJ, vu que ce n'est visible que depuis hier.

**Comment by Far2Casual** [comment]
J'ai pas l'impression que ça soit le cas. Voici un perso (Albert) avec un consommable Huile éthérée : 
![image](https://user-images.githubusercontent.com/63196064/98920823-dc22d580-24d0-11eb-967a-e76fe343625b.png)

J'échange avec un autre perso (Jarem) qui n'a pas le consommable. Je remarque déjà des trucs bizarres dans le chat sur le truc de l'échange : 
![image](https://user-images.githubusercontent.com/63196064/98920965-0a081a00-24d1-11eb-823d-8743c5a087f7.png)

Le consommable est bien retiré du perso de base (Albert) : 
![image](https://user-images.githubusercontent.com/63196064/98921075-2a37d900-24d1-11eb-9f1d-10e6230ccb61.png)

Mais il n'apparaît ni dans la fiche, ni dans les consommables du second personnage (Jarem) : 
![image](https://user-images.githubusercontent.com/63196064/98921149-40de3000-24d1-11eb-8a16-109eae3af57c.png)
![image](https://user-images.githubusercontent.com/63196064/98921202-4d628880-24d1-11eb-8bc5-822f2ca834d5.png)

**Comment by Ulty** [comment]
Il y a un bug, alors. Je m'en occupe.

**Comment by Ulty** [comment]
Ouch, oui, c'est pas du tout à jour avec la nouvelle gestion des consommables, cette fonction !

**Comment by Ulty** [comment]
C'est corrigé chez toi ?

**Comment by Far2Casual** [comment]
Super, et ça fonctionne aussi avec les PNJ et ça s'est très cool pour les trésors ou les boss avec consommables !
