### ISSUE TITLE
Fix/extension resistanceA_

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#167]
1. Sur des personnages repris par des tokens Mook, l'attribut "resistanceA_feu" par exemple ne fonctionne pas. 
Cela vient du fait qu'on fait un "attributeAsBool" au lieu d'un "charAttributeAsBool". Mais si je change l'un par l'autre, je pense que ça casserait un éventuel effet temporaire, par exemple lié à l'absorption d'une potion de résistance, je me trompe ? Je fais un "ou" ?

2. Je peux rajouter le support de resistanceA_tranchant, resistanceA_contondant, resistanceA_percant (ex : golem d'os S9 Anathazerïn) ?

**Comment by Ulty** [comment]
Tu as raison pour le point 1. Le mieux serait peut-être de faire une fonction `charOrTokenAttributeAsBool`, car ce n'est peut-être pas le seul cas comme ça. 

Et oui, tu peux rajouter les autres résistances, mais je préférerais que tu répares d'abord les petits soucis qui restent. Si tu veux, je m'occupe du `sendPlayer` ? Il devrait suffire de mettre en argument de `dmgDirects` le nom du joueur, je pense.

**Comment by Far2Casual** [comment]
Ha je suis désolé en faisant un fetch ce matin j'avais vu que tu avait changé sendPlayer et j'ai incorrectement cru que tu l'avais effectivement fixé. Oui effectivement ça suffira amplement, il faudra juste alors le persister dans l'event pour le bouton chance. Je te laisse t'en occuper ?

**Comment by Ulty** [comment]
Ok, je m'en charge.

**Comment by Far2Casual** [comment]
Du coup je me demande : est-ce que ça ne serait pas mieux de carrément changer le comportement de attributeAsBool, ou de tokenAttribute de cette manière ? 
Ou bien tu vois des cas où on voudrait toujours ne récupérer que l'attribut "token" d'un mook en ignorant l'éventuel équivalent "character" ?
On pourrait aussi faire en sorte que d'abord il considère l'attribut "mook", et que s'il ne le trouve pas il cherche un éventuel attribut "character" ?

**Comment by Ulty** [comment]
@Far2Casual : Oui, je commençais aussi à me poser la question. J'avais bien fait la différence pour pouvoir avoir pour la même fiche un personnage lié et des mooks. Mais en pratique, je ne l'ai jamais fait, et je ne crois pas que ça puisse être utile, autant l'interdire. Le seul soucis serait celui de la performance : ce qui coûte, c'est les appels à `findObjs`, et les recherches dans les tableaux d'attributs. Là on multiplierait par 2 le coût des `attributeAsBool`. Peut-être qu'on pourrait prendre tous les attributs d'un `charId`, puis filtrer par une expression régulière.

**Comment by Far2Casual** [comment]
Ok. je commit déjà la partie sur l'implémentation des nouvelles résistance, et puis je regarde ça. Merci !
