### ISSUE TITLE
Injonction Mortelle

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#172]
Bon comme tu l'auras deviné je suis en train de préparer le scénario 9 d'Anathazerïn et je comble les trous au fur et à mesure que je les vois :). Et le suivant c'est implémenter Injonction Mortelle (R3 Magie Maléfique), ce qui risque d'être très utile pour la suite. 

Je ne vois pas tellement d'autre option que d'implémenter une commande spécifique, à la manière de "Tueur Fantasmagorique". D'accord avec ça ?

**Comment by Ulty** [comment]
Effectivement, il va falloir une commande dédiée, c'est plus simple. L'alternative, c'est d'implémenter un `limiteCibleParCombat` dans le `parseOptions` et les limites, puis d'avoir une syntaxe pour faire des DM en cas de save raté. Je ne crois pas que ça vaille le coup.

J'ai de la chance que tu aies un peu d'avance sur moi, là :)

**Comment by Far2Casual** [comment]
Je ne suis qu'à la fin du S7, mais je prépare déjà le 9 ;)

Bon ce que je vais faire d'abord c'est ajouter l'option du PC pour Tueur Fantasmagorique, comme ça après je reprends la même structure pour l'Injonction Mortelle.
