### ISSUE TITLE
Bug RD "sauf" hache

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#174]
Je n'arrive pas à faire fonctionner la RD_Hache. Pourtant la Hache en durium de mon Guerrier est bien reconnue comme Hache : 
![image](https://user-images.githubusercontent.com/63196064/100326255-02b13800-2fca-11eb-983c-ba597dd9c8d9.png)

Le Sylvanien a bien une RD10/feu_hache : 
![image](https://user-images.githubusercontent.com/63196064/100326326-18bef880-2fca-11eb-979d-ef5c1d55709a.png)

Et pourtant quand le Guerrier attaque : 
![image](https://user-images.githubusercontent.com/63196064/100326429-3f7d2f00-2fca-11eb-97ab-2e932fe49987.png)

**Comment by Ulty** [comment]
J'avoue avoir commité ça tard hier soir, et pas encore testé...

**Comment by Ulty** [comment]
ça marche chez moi, maintenant.

**Comment by Far2Casual** [comment]
Thanks !
