### ISSUE TITLE
PC pour disparition

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#182]
Tu le verras dans #181 , tout est prêt pour supporter les PC et la rune d'énergie sur le test de la capacité de Disparition (voie du Tueur, rang 2). Il suffit de décommenter la ligne avecPC: true

Le problème est celui-ci : au moment où le testOppose est appelé, l'évènement lié n'a pas encore été ajouté dans le journal d'évènements, et n'a donc pas d'ID. L'évènement de l'attaque est fait après, lors de l'appel à resoudreAttaque(). Or un identifiant d'évènement est nécessaire pour le bouton chance.

Deux possibilités : 
- soit refactorer l'ajout de l'évènement d'attaque encore plus tôt, de manière à ce que l'évènement ait déjà un id au moment de faire le jet pour disparition
- soit faire le jet plus tard, dans resoudreAttaque()

Je voulais ton avis avant d'aller plus loin.

**Comment by Ulty** [comment]
Je n'ai pas encore regardé, mais à priori, je pense que je vais essayer d'ajouter l'événement plus tôt, ça me semble le plus logique.

**Comment by Far2Casual** [comment]
Merci !
