### ISSUE TITLE
Limite à la rune de protection

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#183]
Ca te dérange si je crée une petite option de règle (dans dommages) pour limiter les dommages encaissables par la rune de protection ? Proposition assez simple et facilement rétro-compatible : https://www.black-book-editions.fr/forums.php?topic_id=18110&tid=434931#msg434931

**Comment by Ulty** [comment]
Oui, ça me paraît très bien. Je veux bien que tu mettes même cette option active par défaut, en expliquant ça dans la doc.
