### ISSUE TITLE
Options d'évitement + Undo/Redo

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#199]
Un cas d'Undo/Redo d'une attaque, par exemple en cas d'utilisation de bouton Chance, les options qui permettent d'éviter une attaque (Esquive Acrobatique, Rune de Protection, etc) ne sont pas rejouées automatiquement, ce qui rend un pénible l'undo/redo de ce genre d'actions.

**Comment by Far2Casual** [comment]
Pour info ce que j'ai en tête, c'est de stocker dans une structure `choices` qui se trouve dans `evt.action` les choix qui ont déjà été fait pour ces options pré-résolution. Un peu comme ce qu'on a fait pour `rolls`. Un système générique de ce genre permettra ensuite d'implémenter des résolutions automatiques, et pourra être réutilisé pour d'autres choses que les options `preDmg`, par exemple pour le Tour de Force du Barbare.

**Comment by Ulty** [comment]
Oui, ça me paraît une bonne idée, cette structure.
