### ISSUE TITLE
Chair à canon et attaques "ratées" qui infligent des dégâts.

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#200]
Petite amélioration à envisager : stocker 3 niveaux de réussite d'attaque au lieu de 2, en rajoutant "réussite partielle". C'est utile sur des attaques à cibles multiples (sorts de zone, balayage, etc).

Actuellement, quand une attaque ne touche pas toutes ses cibles, l'attaque n'est pas mise en "réussite". C'est important dans certains cas (par exemple pour savoir qu'on peut proposer un bouton Chance), mais dans d'autres cas ça génère des bugs. Deux rencontrés récemment : 
1. Chair à Canon sur une attaque qui touche deux cibles mais l'une n'est pas touchée, le bouton va bugger
2. Des munitions spéciales avec attaques de zone (ex :  carreau explosif), si elles ne touchent pas toutes les cibles elles ne sont pas consommées automatiquement et le joueur a une chance de les ramasser.

**Comment by Ulty** [comment]
Je ne suis pas sûr que le niveau réussite partielle aide, ici. Pour les boutons chances, on veut une occasion de l'utiliser dès qu'une cible n'est pas touchée, non ? Pour les munitions explosives, elles devraient toujours exploser, même si on rate toutes les cibles. Pour la chair à canon, je ne suis pas sûr de savoir pourquoi ça bug, il faudrait regarder ça de plus près.

**Comment by Far2Casual** [comment]
T'as complètement raison je suis idiot pour le carreau explosif. Et pour chair à canon je sais ce qui s'est passé en fait, c'était sur une boule de feu et le magicien a raté son jet de touche, mais la boule de feu fait des dégâts quand même. Le bouton Chair à Canon est apparu, mais je n'ai pas pu l'utiliser, il indiquait : 

![image](https://user-images.githubusercontent.com/63196064/103995354-aa5c8100-5198-11eb-88fc-11a8ca94f78d.png)

Bon du coup je renomme la story qui est beaucoup moins grosse et uniquement centrée sur chair à canon.

**Comment by Far2Casual** [comment]
J'ai fini tous les cas de testCaracteristique ! :D. Je te ferai un PR avec ce qui reste. 

Par contre, ton bugfix m'a fait trouver un gros bug dans le redo d'attaques et les éventuels dommages additionnels. Ils sont à la fois persistés et recalculés, cela fait parfois des erreurs de calcul, et parfois tout simplement planter le script.
