### ISSUE TITLE
Toiles : icône & save par tour

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#202]
Hier j'ai utilisé Toiles (je finis le S8) et : 
- les saveParTour ne s'affichaient pas (pas hyper grave mais j'ai du faire manuellement)
- il n'y a pas d'icône sur le token du perso (pas franchement nécessaire, mais ça pourrait être sympa)

**Comment by Ulty** [comment]
Pour les icones, je viens de faire l'essai et j'ai bien l'icone. Je pense que tu as probablement supprimé les icones par défaut dans ta partie, car l'icone fait partie de ceux-là. Je n'en vois aucun qui convienne (pour l'instant) dans les icones custom COF.

**Comment by Far2Casual** [comment]
Merdoum :)

J'ai suivi le message de la console qui dit que je pouvais les supprimer, j'aurais pas dû donc ;)

**Comment by Ulty** [comment]
Je crois que je vais enlever ce message, en effet...

**Comment by Ulty** [comment]
Si  ca marche pour toi, tu peux fermer l'issue. Éventuellement, @Bleuzaille pourrait nous rajouter un bel icone pour l'effet entoilé ?

**Comment by Far2Casual** [comment]
Merci !
