### ISSUE TITLE
Amélioration effetRetarde

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#207]
Autre truc qui est survenu dans notre combat avec les Elfes Noirs, c'est le poison à effet retardé de nos amis poètes. J'avais utilisé : 
`--effet effetRetarde(endormi) 1d6 --save CON 12`

Grosso modo ça a fonctionné, mais la seule chose que ça fait tel quel c'est un petit whisper automatique au joueur du personnage avec le nom de l'effet (ici : endormi), et un message dans le chat "effet activé". J'avoue que du coup, je l'ai raté, et à la fin du combat j'ai réalisé que j'avais complètement oublié d'endormir un des PJs.

De plus, je viens de tester et l'option --valeur n'est pas très utile, on peut juste mettre un mot (un espace va casser le parsing) qui sera lui aussi uniquement whisper au joueur contrôlant le personnage.

Tu avais autre chose en tête avec cette option, ou bien c'est moi qui l'utilise mal ?

**Comment by Ulty** [comment]
Oui, c'était juste pour afficher un message au bout d'un certain temps. Tu voudrais activer une action au bout d'un certain temps ? On devrait pouvoir utiliser `--valeur` pour ça à la place, c'est vrai.

**Comment by Far2Casual** [comment]
C'est un peu l'idée, ce serait super cool de pouvoir faire --effet effetRetarde(endormi) 1d6 --valeur endormi --save CON 12 et après 1d6 tours le perso chope l'état endormi automatiquement. C'est vraiment un nice to have évidemment :)

**Comment by Ulty** [comment]
Je pense que `effetRetarde `est un mauvais mot clé pour ce que ça fait actuellement. Je vais le renommer en `messageRetarde`, et laisser `effetRetarde `prendre en argument un état ou un effet, avec la convention que pour un effet temporaire la durée par défaut est de 1 tour et qu'on peut la changer dans valeur.

**Comment by Ulty** [comment]
@Far2Casual : C'est bon comme ça pour toi, on peut fermer l'issue ?

**Comment by Far2Casual** [comment]
Yup !
