### ISSUE TITLE
Bugs charge fantastique + undo/redo

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#208]
Je remarque certains effets de bord lors d'attaques liées à la Charge Fantastique en cas d'undo/redo.

Par exemple, si une attaque rate et qu'on utilise un PC, ou même la capacité "Exemplaire", le D6 aux dégâts est ajouté plusieurs fois. Exemple : 
![image](https://user-images.githubusercontent.com/63196064/104089753-b9633200-5271-11eb-8f36-b871f06de694.png)

De plus, utiliser un PC a un comportement étrange, l'affichage présente toujours un "1" au D20, et pourtant l'attaque touche quand même. Wtf ?
![image](https://user-images.githubusercontent.com/63196064/104089891-d9dfbc00-5272-11eb-974b-dc83c397be3d.png)

**Comment by Ulty** [comment]
C'est très bizarre, le coup du 1 au jet !
