### ISSUE TITLE
Bugs de RD

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#219]
Non ça n'allait pas. J'ai vu divers trucs qui sont potentiellement un jour à changer / fixer : 
- les valeurs négatives de RD ne sont pas bien gérées (à certains endroits on ne les exécute que si > 0, ça devrait être != 0)
- X/tranchant ne fonctionne pas
- hache:X ne fonctionne pas non plus.

_Originally posted by @Far2Casual in https://github.com/Ulty/COFantasy/issues/217#issuecomment-760239158_

**Comment by Ulty** [comment]
Alors je n'ai pas réussi à reproduire le problème avec x/tranchant. Au premier essai, en tout cas, ça marche comme il faut. Tu peux réessayer, @Far2Casual ?

**Comment by Far2Casual** [comment]
Tu as raison, le X/tranchant ça a l'air d'aller. J'ai du me planter dans mes tests l'autre jour. 🤔

**Comment by Far2Casual** [comment]
Par contre pour les RD négatives, le code du 15/1, 14:46 ne semble pas suffisant : 
![image](https://user-images.githubusercontent.com/63196064/104734443-8c66c180-5740-11eb-9253-644467f58cec.png)

**Comment by Far2Casual** [comment]
Ca marche ! Merci !
![image](https://user-images.githubusercontent.com/63196064/104810372-5551e800-57f4-11eb-98c3-583cc8fd67d8.png)
