### ISSUE TITLE
"niveau" d'un PNJ

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#225]
Ceci a des conséquences potentiellement assez ennuyantes : https://www.black-book-editions.fr/forums.php?topic_id=4800&tid=443885#msg443885

Grosso modo jusqu'à présent je jouais incorrectement mes PNJ comme si leur NC = leur niveau. En fait c'est faux, ça se voit sur les PJs d'Anathazerïn, mais aussi dans les règles de conception de créature p. 218, il faut bien deux niveaux de profils à un PNJ pour qu'il gagne 1 NC.

Du coup, certaines capacités comme implémentées actuellement, sont incorrectes. Je prends l'exemple de l'attaque étourdissante du Psionique qui en fait ne devrait marcher que sur des créatures au NC inférieur ou égal à la moitié de son niveau.

Comment faire ?

**Comment by Ulty** [comment]
On pourrait, chaque fois qu'on cherche le niveau d'un personnage, le multiplier par 2 si il a une fiche de type PNJ. Mais je vais peut-être d'abord poser la question sur le forum.

**Comment by Far2Casual** [comment]
Je crois qu'on peut close après la réponse de Laurent 😅
