### ISSUE TITLE
Tour de force & Pacte Sanglant

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#226]
Petite question pour toi mon cher @Ulty. Contrairement aux autres capacités déjà implémentées, ma lecture de Tour de Force et de Pacte Sanglant ne semble par permettre aux personnages d'ajouter le bonus **après** un jet, mais ils doivent être décidés **avant** un jet. Cela pose donc un problème sans précédent car nous n'avons pas de système générique qui consiste à "interrompre" une action avant un jet pour demander si le joueur veut ou pas utiliser cette compétence.

Du coup, je me tâte un peu. Si au moindre jet, par exemple un jet de sauvegarde dans une attaque, on interrompt la partie avec un bouton "Utiliser Tour de force / Pacte Sanglant" et un autre "Continuer", n'est-ce pas un peu disruptif ?

Sinon, est-ce qu'on crée une commande qui permet l'utilisation de la compétence, et qui met un attribut temporaire jusqu'au prochain jet pour appliquer le bonus ? Mais du coup alors, comment faire pour les jets de sauvegarde par exemple, dont on sait s'ils sont à faire qu'après avoir résolu une partie de l'attaque (ex : fauchage sur 15+ au dé de touche).

**Comment by Ulty** [comment]
Je ne suis pas sûr de comprendre ça comme toi. Pourquoi penses-tu que le personnage doive décider avant le jet ? Moi, ça ne me semblerait pas trop puissant qu'on puisse le faire après, et ça m'arrangerait drôlement pour le script...

**Comment by Far2Casual** [comment]
Dans le cas d'un PC, ou d'une rune d'énergie, on parle spécifiquement de relance.
Dans le cas de prouesse, il y a une phrase qui dit explicitement que ça peut être utilisé après le jet, et une fois par tour.
Ce n'est indiqué dans aucun des deux autres cas.

**Comment by Ulty** [comment]
Pas si sûr. On est à la limite de la sur-interprétation. J'ai déjà vu d'autre aspects des règles où quelque chose était parfois spécifié, parfois non. Et non spécifié ne signifie pas forcément que le contraire est vrai. Cela dit il est quand même très possible que tu aies raison, mais je vais quand même poser la question avant qu'on s'engage dans un truc compliqué.

**Comment by Far2Casual** [comment]
Ca me va. Et franchement je n'ai pas d'avis obtu sur la question, si on peut l'activer a posteriori je l'implémente comme ça, ça sera BEAUCOUP plus simple 😅

**Comment by Ulty** [comment]
Suite aux réponses de Kegron, le tour de force n'est pas utilisable sur les saves. Et pour le pacte sanglant, c'est quand même un rang 3, avec un coût en PV, ça ne me semblerait pas abusé de l'autoriser en réaction, mais avant de savoir le résultat de l'attaque pour le bonus en DEF.

**Comment by Far2Casual** [comment]
Ouais, on va faire ça en version "simple". En fait, un peu comme on gère "Intercepter" du chevalier au final. J'oblige mes Chevaliers à déclarer avant l'attaque s'ils désirent intercepter une attaque, même si en pratique dans le script ils cliquent sur le bouton après la résolution. On peut très bien laisser au MJ le fait de gérer ces déclarations de cette manière-là aussi.

Je m'occupe de faire de ces deux capacités un bouton géré de manière générique, comme pour petit veinard par exemple.

**Comment by Ulty** [comment]
Merci !
