### ISSUE TITLE
Bug des esquives acrobatiques et autres si 2 cibles

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#232]
Je viens de voir que dans le cas de cibles supplémentaire (--target, utilisé pour le balayage), l'esquive acrobatique bug : on voit 2 fois d'affichage des information du barde.

**Comment by Far2Casual** [comment]
Je n'arrive pas à reproduire Ulti, tu peux préciser ? Ci-dessous mon test : 

Attaque avec Balayage : 
![image](https://user-images.githubusercontent.com/63196064/105734796-5214d580-5f33-11eb-8d60-befbc889eabd.png)

Esquive Acrobatique : 
![image](https://user-images.githubusercontent.com/63196064/105734909-68229600-5f33-11eb-8e39-1fd3d129ad3d.png)

Continuer : 
![image](https://user-images.githubusercontent.com/63196064/105734950-74a6ee80-5f33-11eb-9940-98bd608f3786.png)

**Comment by Far2Casual** [comment]
Ha je l'ai ! En cas de réussite en fait : 
![image](https://user-images.githubusercontent.com/63196064/105736128-c0a66300-5f34-11eb-8dc4-92586e375e57.png)

**Comment by Far2Casual** [comment]
Je te laisse close si le problème que tu as rencontré est résolu.

**Comment by Ulty** [comment]
Oui, ça me semble résolu. Merci !
