### ISSUE TITLE
Passer les feux grégeois en !cof-attack

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#234]
Une raison qui s'opposerait au fait de passer les feux grégeois en !cof-attack (au lieu de !cof-dmg actuellement) ? Car une série de choses ne marchent pas sur cof-dmg, comme une rune de protection par exemple.

**Comment by Ulty** [comment]
Non, aucune raison de s'y opposer. Ça me semble même plus logique de réserver `!cof-dmg` aux cas où il n'y a pas de personnage source des dégâts.
