### ISSUE TITLE
Bug AoE et redo

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#236]
J'ai rencontré un bug très étrange sur les AoE et les undo/redo, une cible "disparaît" : 

1. AoE 
![image](https://user-images.githubusercontent.com/63196064/105860196-9c5a8d00-5fed-11eb-8673-9927ff6e0888.png)

2. Rune d'énergie
![image](https://user-images.githubusercontent.com/63196064/105860279-b005f380-5fed-11eb-9b48-d7a5cbd4fd8f.png)

3. ???
![image](https://user-images.githubusercontent.com/63196064/105860323-b98f5b80-5fed-11eb-8fa2-d14c6a9629f2.png)

Reproduisible sur cof-dmg aussi d'ailleurs.

**Comment by Far2Casual** [comment]
Ok c'était fourbe, juste qu'on repassait toutes les cibles dans un filtre de distance en cas de redo, hors c'est inutile.

**Comment by Ulty** [comment]
Bravo pour le fix :)
