### ISSUE TITLE
Améliorations Charge Fantastique

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#240]
Quand je l'utilise moi-même en tant que MJ, charge fantastique est clair, mais pour l'instant avec mon groupe de joueurs, ils ont du mal à comprendre comment ça fonctionne. Les améliorations qui seraient sympas sur la fonctionnalité actuelle : 

- [x]  Empêcher un joueur d'appuyer deux fois sur son bouton j'ai bougé (sinon ça fait un peu tout foirer)
- [x] Indiquer un feedback à tous sur l'état du pseudo-tour de charge fantastique. Les joueurs reçoivent un pop up d'action quand c'est à leur tour de jouer, mais sinon on ne voit rien et c'est dur de savoir où on en est. Peut-être déplacer l'affichage du joueur actif ?
- [ ] Ajouter un bouton dans une attaque de charge fantastique qui permet au joueur de dire "next" aussi, comme pour les mouvements.

**Comment by Ulty** [comment]
Effectivement, un meilleur suivi de la personne dont c'est le tour pendant la charge pourrait être intéressant.

Pour le troisième point, c'est pareil que de laisser le joueur passer au suivant dans un combat normal, non ? Si c'est ce que tu veux, tu peux leur mettre `!cof-tour-suivant` en macro ou dans les actions, ça devrait revenir au même.

**Comment by Far2Casual** [comment]
Le troisième point n'est pas vraiment indispensable. En fait avec quelques petits tweaks, on peut déjà faire bouger l'aura du joueur actif en fonction des actions, et ça va déjà bien aider.

Je te pushe ça bientôt.

**Comment by Far2Casual** [comment]
Bon j'ai bien pu tester hier en conditions réelles, et ça marche comme sur des roulettes 😄
