### ISSUE TITLE
Armée des morts

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#243]
Je cherche à terminer la Voie de l'Outre-tombe, parce que j'envisage de faire affronter des Nagas à mes PJs. Et ces sorts sont particulièrement costauds à gérer, donc l'automatisation au moins partielle est d'une très grande aide.

Alors pour ce sort (hyper puissant), mon idée : 
- utiliser une aura de token pour symboliser la zone, pratique puisque la zone suit en effet le lanceur
- me baser sur l'implem des auras pour les dommages
- pour l'action limitée de défense, ajouter un bouton spécifique dans la liste d'action du joueur

Questions : 
1. Je compte utiliser l'aura 2 des tokens pour afficher la zone. Es-tu d'accord ? Je documenterai ce fait afin que ce soit clair pour les joueurs. Mettre l'effet active l'aura, supprimer l'effet (la retire).
2. Pour les dégâts, je vérifie tous les tokens au début de chaque tour, comme pour les auras. Dans ce cas-ci, j'utilise cof-dmg. Comme les dégâts peuvent varier d'un token à l'autre (3D6 & 1D6), je crois qu'on est forcés de faire les dommages tokens par tokens. Ok ?
3. Si je dois vérifier à chaque tour de chaque token s'il est où pas dans une armée des morts, afin d'ajouter ou pas l'action supplémentaire, j'ai peur que ça devienne vite très lourd. Du coup, je compte simplifier et utiliser un champ de stateCOF pour savoir si une armée est active, et si oui je propose l'action à tous les tokens. Dois-je faire la différence alliés ou pas, ce qui inclut une structure de données plus compliquées ? Pour les dommages, la différence alliés / cibles est évidemment faite.
4. Pour l'action, je compte faire une commande spécifique qui met un champ précis du token à true. Lors des dommages sur un token, je me base sur cet attribut pour décider 3D6 ou 1D6 dégâts. Ces attributs sont tous supprimés ensuite. Ok ?

**Comment by Ulty** [comment]
Ok, pour l'aura 2, elle n'est pas utilisée par le script. Mais si tu as un peu de temps ce serait plus cool de mettre un gros token d'armée des morts, qui se place sous le nécromancien et se déplace avec lui, non ?

Pour les dégâts, si tu utilises un effet d'aura, il n'y a rien à implémenter ? Peut-être juste une option à !cof-dmg pour faire moins de dégâts quand un attribut est présent (qui correspondrait à un personnage qui se défendrait).

Pour le point 3, on pourrait peut-être ne proposer l'action qu'aux tokens à portée de l'armée des morts, non ? Si on ne fait la recherche que quand une armée des morts est présente, ça ne devrait pas être trop coûteux.

Je te laisse décider, en fonction aussi du temps que tu as à y consacrer ; ton plan original est largement suffisant.

**Comment by Far2Casual** [comment]
Je vais retravailler sur base des suggestions.

Pour les dommages et l'aura si, dans tous les cas il faut implémenter un truc spécifique. La vérification d'un attribut & changer complètement le roll de dommages en particulier.
