### ISSUE TITLE
Invocation Démon/Squelette

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#247]
@Ulty : pour la cohérence et le maintien du script, je me demande si ça ne serait pas mieux que tu t'occupes de créer et de hoster les avatars et les tokens utilisés par les compétences d'invocation. Je vois que tu l'as déjà fait pour l'invocation d'un prédateur, penses-tu pouvoir le faire aussi pour le Démon et le Squelette ?

Et tu m'envoies ensuite les liens AWS que j'intègre dans le code.

**Comment by Ulty** [comment]
Oui, tu as raison, même si je réfléchis sérieusement à passer sur Foundry VTT en ce moment.

**Comment by Ulty** [comment]
Déjà une proposition pour le démon : `https://s3.amazonaws.com/files.d20.io/images/183633585/DWpHYp4SLPCDCMHdmTyKOw/thumb.png?1607339938`

**Comment by Ulty** [comment]
Pour le squelette, j'ai `https://s3.amazonaws.com/files.d20.io/images/147478849/xlt8DCOtOqq4pQbXqJII-A/thumb.png?1593637048`. C'est celui que je préfère, mais si tu n'aimes pas trop, jai aussi `https://s3.amazonaws.com/files.d20.io/images/29280162/yE969j48uDK89Roil4qlRg/thumb.png?1487951226`

**Comment by Far2Casual** [comment]
Merci, j'ai déjà repris le démon. Je vois qu'on utilise les mêmes ressources 😉 

Et pour FoundryVTT, faut vraiment qu'on en parle à l'occasion. Le VTT a l'air 100 fois mieux, et si on refait ce qu'on a fait ici sur ce VTT-là, y aura plus grand chose qui me retiendra sur roll20 non plus.

**Comment by Far2Casual** [comment]
Sry mais en fait, c'est un Zombie qu'il me fallait pour refaire Animation des Morts :P

**Comment by Ulty** [comment]
Alors je peux te proposer `https://s3.amazonaws.com/files.d20.io/images/147503510/RKFKQefVjSiyNPJtvBuGOg/thumb.png?1593643543`

**Comment by Far2Casual** [comment]
Ok j'ai une version qui marche mais je me pose quand même quelques questions.

Pour Invocation d'un Démon, j'ai clairement lié ça à un "combat", car la durée est fixe. Quand le combat s'arrête, le Démon est automatiquement supprimé.

Pour Animation des Morts, j'aimerais un peu ton avis. Car il n'y a pas de durée fixe pour un Zombie, le Zombie a 12 PV, en perd 1 toutes les minutes, mais on pourait donc imaginer un Zombie qui suit un Nécromancien sur plusieurs minutes, ce qui dépasse le cadre d'un combat. Il arrivera peut-être donc des situations où on voudra avoir des Zombies "hors combat". Mais si c'est le cas, la gestion des Zombies devient un peu compliquée, car je ne peux pas automatiquement "nettoyer" les état à la fin d'un combat.

Alors à ton avis, il vaut mieux quoi : 
1. Je simplifie et Animation des Morts lance forcément l'initiative et met tout le monde en combat, et à la fin de celui-ci on détruit tous les Zombies ? Cela permet de gérer la dégradation automatique et le nombre maximal de Zombie facilement, car on reset tout à la fin.
2. Je permets l'invocation de Zombie hors combat, mais alors la gestion du nombre maximal de Zombie devient beaucoup plus compliquée car il faut quasiment implémenter un nouveau système qui détecte la suppression d'un Zombie sur la carte pour gérer le max. Et surtout j'ai peur que si on change de carte en ne supprimant pas les Zombies invoqués sur l'autre on risque de ne pas comprendre pourquoi la limite n'est pas reset.

**Comment by Ulty** [comment]
Pas facile. Je dirais quand même que l'utilisation principale du zombie, c'est en combat. Sans compter la perte de PV toutes les minutes qui peut se compter en combat. Donc je ferais juste la version combat. Et si on en a besoin hors combat, on peut toujours faire un combat artificiel. Et au pire, simplement utiliser un zombie PNJ.
