### ISSUE TITLE
Bug undo sur !cof-init

### ISSUE THREAD

**Issue by waibcam** [Ulty/COFantasy#25]
Re,

Alors rien de majeur mais j'ai remarqué un bug ce matin en testant le undo sur le **Turn Order**.
Situation : !cof-init sur au moins 2 tokens A et B

Si on passe le tour de A, le flag va sur B.
Si ensuite on undo, le flag revient bien sur A mais si on passe le tour de A, le flag ne va pas sur B (il reste sur A) et il faut passer encore le tour pour que ca fonctionne correctement.

Pour info : 
- Si on utilise #TurnAction#, on voit bien que ce dernier n'est pas rappelé quand on fait le undo .
- Le souci est bien entendu existant avec l'option "--aura"
- Le bug n'est a priori pas causé par "--aura" car il était présent dans la version avant ma modif : https://github.com/Ulty/COFantasy/blob/8a0b3c420a6dbcab34ca986f456ffe3126bc2198/COFantasy.js

**Comment by Ulty** [comment]
Le premier tour de combat n'est pas évident. Si je me souviens bien, il y a 2 événements de changement de turnorder la première fois qu'on clique sur le suivant. Je m'étais bien pris la tête pour avoir un undo cohérent, mais apparement c'est pas encore parfait. Je vais regarder ça...

**Comment by Ulty** [comment]
Si c'est bon pour toi, tu peux fermer l'issue.

**Comment by waibcam** [comment]
Ca a l'air bon !
Merci :)
