### ISSUE TITLE
Ajouter le support de la tempête de mana pour Ténèbres

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#253]
Avec la dernière version, plus moyen d'utiliser les options de tempête de mana.

**Comment by Far2Casual** [comment]
@Ulty j'ai l'update prêt mais ça nécessite de changer la syntaxe de la commande Ténèbres (notamment par exemple pour laisse la possibilité d'augmenter la portée avec Tempête de Mana, je dois me débarasser de la partie --disque 5 20). Tu veux que je fasse une migration d'ability, ou bien tant pit ?

**Comment by Ulty** [comment]
Mais du coup il n'est plus possible de préciser la portée ou le rayon des ténèbres ?

**Comment by Far2Casual** [comment]
Pas besoin. La portée standard c'est 20m, le rayon 5m, donc c'est "hard codé".
Et les options magiques :
--puissant passe le rayon à 7m
--puissant portee passe à 40m
--puissant duree double la durée

Est-ce que c'est vraiment nécessaire de gérer portée et rayon "manuellement" ?

**Comment by Ulty** [comment]
Oui, ça me semblerait potentiellement utile : utilisation d'un sort plus puissant pour un PNJ ou une voie de prestige, utilisation de règles maison, possibilité pour un PJ de faire quelque chose de plus fin (si il veut une zone d'ombre de seulement 2 m de rayon, par exemple par la Voie de la mana, je pourrais autoriser ça), etc...

Quelles sont les difficultés à avoir ces paramètres optionnels pour la commande ? Ce serait beaucoup de boulot ?

**Comment by Far2Casual** [comment]
Non pas vraiment, j'avoue que je ne pensais pas ça utile.
Dis-moi ce que tu voudrais avoir comme spec et je rajoute ça !

**Comment by Ulty** [comment]
Pourquoi pas une option `--portee` et une option `--rayon` ?

**Comment by Far2Casual** [comment]
Voili voilou.
Pour info j'ai fait de l'option "rayon" un truc générique (géré par parseOptions donc), ça pourra être utile dans le futur pour des options de sorts à disque dont on veut faire évoluer le rayon avec d'autres options comme Tempête de Mana. La sélection --disque X X ne l'étant elle pas.

**Comment by Ulty** [comment]
Issue résolue, donc !
