### ISSUE TITLE
Etreinte scorpion

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#257]
Je réfléchis déjà un peu à l'avance et je me pose une question sur l'étreinte du scorpion (Anathazerïn p. 415).

Cette étreinte est un peu étrange dans le sens où si un personnage est étreint, il doit faire un test au début de son tour ou être étourdi. Mais comment tu veux implémenter ça ? Le test n'est pas "automatique au début du tour", car ça doit se passer au tour du joueur. Mais si tu mets un personnage étourdi, il n'aura pas sa liste d'actions car il est "inactif".

Ce que j'avais en tête, c'est que plutôt de le mettre étourdi, on le mettrait "immobilisé" avec un statut spécial qui diminue sa DEF de 5, et de faire sinon la même chose que ce que tu as fait pour Etreinte avec Immolation (bouton dans la liste action, test spécifiquement avec 1D20).

**Comment by Ulty** [comment]
Je pense que le plus simple est de modifier un peu la capacité pour avoir un test au début du tour au lieu du début du tour du joueur. Contrairement à étreinte, c'est un test qui ne demande pas d'action, ça se rapproche plus de la prison végétale, en fait. Donc on peut faire automatiquement un test. Si tu veux vraiment respecter la règle à la lettre, on peut lancer le test et ses conséquences au moment de passer au tour du joueur, mais ça me semble moins de boulot de faire ça avec les autres effets de changement de tour.

**Comment by Far2Casual** [comment]
Je pense que ce serait le plus simple, oui, mais ça ne serait pas vraiment faire honneur à la capacité je trouve, car l'idée est que ça ressemble vraiment à une étreinte et que le joueur doit bel et bien "agir" pour se libérer. Du coup, quitte à modifier la capacitén c'est plutôt le fait d'être étourdi que je changerais, ça n'a pas vraiment de sens, comment peut-on se libérer d'une étreinte si on ne peut pas agir ?

Donc je propose plutôt d'aligner cette étreinte sur celle du démon gardien des Jardins (immobilisé, test de FOR opposé avec D20), sans malus de DEF sur le scorpion, et avec 1D6+3 dégâts auto. Ca me paraît beaucoup plus "en ligne" avec la logique des autres capacités similaires, et c'est très facile à coder.

Qu'en dis-tu ?

**Comment by Ulty** [comment]
Je ne suis pas sûr que le joueur doive "agir" : le test est obligatoire, ça ne consomme aucune action, qu'elle soit limitée ou de mouvement. Pour moi ça ressemble plus à un test de résistance pour ne pas sombrer dans l'inconscience ou dans la douleur. Sinon, qu'est-ce qui l'empêche de ne pas "agir" pour se libérer et faire une grosse attaque psychique à la place ?

Comme le joueur n'a pas le choix entre faire le test ou pas, je serais plutôt quand même partisan de le faire automatiquement. On peut imaginer un état spécial qui permet de ne pas être enlevé du turn tracker mais de lancer le test opposé au tour du personnage. Ou bien proposer juste le bouton si tu préfères que le joueur se sente plus impliqué. C'est vrai aussi que le test automatique rend difficile l'utilisation de points de chance.

Pour résumer, pour moi c'est un test de résistance à la pression. Pour que le joueur ait un peu la main sur son destin (et en particulier puisse utiliser sa chance) c'est peut-être mieux de proposer une seule "action" à son tour. Pour ça, l'attaque du scorpion met un attribut sans autre effet que modifier la liste d'actions affichée. Puis si le test opposé rate, on met juste un malus de -5 en DEF (avec un deuxième attribut, genre etourdiParEtreinte).

**Comment by Far2Casual** [comment]
Oui, ça rejoint nos deux idées je pense. Si je résume : 
- un état spécial qui diminue la DEF de 5 mais ne retire pas du Turn Order
- la liste d'actions est remplacée par juste un bouton pour le jet de FOR opposé. S'il est raté, 1D6+3 dégâts, s'il est réussi retrait de l'état et liste d'actions normale.

Je tente ça ?

**Comment by Ulty** [comment]
C'est ça, mais il faudrait 2 états (ou attributs) : 1 pour n'avoir que le jet de FOR opposé en liste d'actions et 1 pour le -5 DEF. Car tel que je lis la capacité, tant que le personnage n'a pas raté un jet de FOR opposé, il n'a pas le malus en DEF. Il faudrait aussi réfléchir à un moyen de rendre ce 1d6+3 DM paramétrable, histoire de pouvoir facilement adapter l'opposition...

**Comment by Far2Casual** [comment]
Ok, c'est noté !

**Comment by Far2Casual** [comment]
Alors voici ce que j'ai : 
1. L'attaque touche et le scorpion étreint.
![image](https://user-images.githubusercontent.com/63196064/111352910-01913d00-8685-11eb-95d3-c4a92765322d.png)
2. Le perso n'a pas encore le malus.
![image](https://user-images.githubusercontent.com/63196064/111353017-24235600-8685-11eb-9e0c-df38ed4851ed.png)
3. A son tour il ne reçoit qu'un bouton pour se libérer (j'utilise déjà ça pour enseveli en fait).
![image](https://user-images.githubusercontent.com/63196064/111353179-546af480-8685-11eb-9c6f-44e4398c6be3.png)
4. S'il rate, il prend les dommages. Les boutons de rerolls sont actifs.
![image](https://user-images.githubusercontent.com/63196064/111353269-6cdb0f00-8685-11eb-9f12-ea3c72fdf20e.png)
5. Du coup il a -5 en DEF contres les attaques
![image](https://user-images.githubusercontent.com/63196064/111354153-4a95c100-8686-11eb-93b4-52bd39a566e2.png)
6. Et s'il se libère, il reçoit sa liste d'actions automatiquement
![image](https://user-images.githubusercontent.com/63196064/111354248-6600cc00-8686-11eb-8c28-b29e4af6a8c5.png)

Pour l'instant et j'ai pas fait l'option de customiser les dégâts de l'étreinte, car même dans la voie de prestige (p. 96) le 1D6+3 semble "hard codé". A faire plus tard si nécessaire quoi.

**Comment by Ulty** [comment]
Ça me semble très bien tout ça ! Bravo !
