### ISSUE TITLE
Documentation "options de mana"

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#271]
Ca te dérange si je fais une passe dans la doc pour centraliser un peu la doc sur la partie "Mana" ? Je dirais : 
1. Donner un peu plus d'infos en haut (juste avant règles optionnelles, faire une section à part) pour documenter toutes les options, leurs possibilités et que faire pour les utiliser.
2. "Nettoyer" la doc des capacités qui fait soit de la répétition, soit ne documente qu'une seule option, ou parfois un mix de tout.

**Comment by Ulty** [comment]
Oui, pour le point 1., ça manque vraiment. Pour le point 2., je ne sais pas trop. J'aime bien pouvoir facilement copier-coller une capacité. Et ça donne des exemples d'utilisation. Mais en même temps, c'est vrai que ça simplifierait la présentation.

**Comment by Far2Casual** [comment]
Ce qu'il y a avec le point 2, c'est qu'en gros le coût en Mana est écrit en "dur" avec le système de base, alors qu'il y a des gens qui n'utilisent pas la Mana, ou que le coût en question est de toute façon incorrect si la personne joue en Mana Totale ou en Terres d'Arran. Mais c'est vrai que si on le met pas, on doit le rajouter "à la main" et on va vite oublier.

Alors je te propose ceci : je laisse --mana avec le coût des règles de base, mais je mets la valeur en évidence (genre en italique) comme ça on montre que ça peut être adapté.

Dernière chose : je pense aussi rajouter systématiquement la version "objet de sort" des aptitudes, pour les parchemins, baguettes et autres objets de pouvoir.

**Comment by Ulty** [comment]
Ça me paraît très bien. Merci !

**Comment by Far2Casual** [comment]
Et j'en profite d'ailleurs pour documenter les abilities qui ne le sont pas mais qui peuvent déjà être implémentées. C'est cool parce que pour les classes de base, ça montre à quel point on couvre vraiment beaucoup des voies de base maintenant !
