### ISSUE TITLE
V2 capacités qui procurent une nouvelle attaque

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#273]
Voici les capacités que j'ai recensé qui permettent, lorsqu'elles sont activées, d'utiliser un nouveau type d'attaque. Jusqu'à présent, on conseillait de créer une nouvelle attaque, conditionnée à l'utilisation par une option `--si`. Comme elles vérifient toutes qu'un état est en cours, je pense qu'on pourrait, sans trop d'effort, remplacer cette partie de setup ennuyante par la génération automatique d'une attaque lors de l'appel à `!cof-liste-actions` directement. Ca faciliterait aussi beaucoup les objets de sorts de ces capacités.

- [ ] Sous tension (Ensorceleur, Voie de l'air)
- [ ] Epée dansante (Ensorceleur, Voie de l'invocation)
- [ ] Mutation offensive (Invocateur, Voie des mutations)
- [ ] Aspect de la succube (Nécromancien, Voie du démon) 
- [ ] Aspect du démon (Nécromancien, Voie du démon)
- [ ] Arme d'argent (Prêtre, Voie de la foi)

Et dans le même genre :
- [ ] Strangulation (Nécromancien, Voie de la Sombre magie) devrait proposer le bouton pour maintenir la Strangulation automatiquement également

**Comment by Ulty** [comment]
Ça fait un moment que j'ai en tête un système qui n'afficherait que les attaques disponibles. Ce que tu proposes est déjà une bonne solution pour une partie du problème, ça améliorera déjà les choses à peu de coût, effectivement.

**Comment by Far2Casual** [comment]
Oki, qu'entends par "attaques disponibles" ? Au contraire de quoi ?

**Comment by Ulty** [comment]
Je pense aux attaques ou actions qui sont possibles sous condition : les utilisations d'objets ou de capacité avec limite de nombre d'utilisations, armes chargées ou non, condition `--si` dans l'attaque, etc. Je pensais essayer de ne présenter dans la liste d'actions que celles qui sont effectivement possibles. Mais ton idée résout déjà une partie du problème sans trop d'effort, donc je pense que c'est bien de le faire.

**Comment by Ulty** [comment]
En fait, en y réfléchissant, je ne suis pas sûr que ça aide vraiment de se limiter au cas de ces attaques activées par une capacité. J'ai en effet l'impression qu'il faudra toujours une ligne d'attaque (pour appliquer des bonus, du genre +1 en att./DM pour les sorts d'un type donné), et du coup ça va demander une mécanique supplémentaire à implémenter. Il serait peut-être plus profitable de faire comme je l'imaginais : ne pas afficher les actions impossibles de la liste d'actions. Dans un premier temps, celles avec un `--si`, par exemple.

Mais de toutes façons, les deux méthodes doivent gérer le cas des attaques qui peuvent être utilisées dans le même tour que leur activation, par exemple à cause d'un effet de hâte. Et dans tous les cas l'épée dansante qui est utilisable en action gratuite, donc dans le même tour que le lancer du sort (selon mon interprétation). Pour ces cas, j'imaginais afficher un nouveau bouton ou bien faire réafficher la liste d'action, mais je ne suis pas encore décidé.

**Comment by Far2Casual** [comment]
Ouais j'étais en train de penser à la même chose, et en réalité il ne faut pas aller chercher très loin, Anathazerïn propose deux objets qui permettent de lancer Sous tension et un bâtonnet métallique qui donne +2/+2 aux attaques d'électricité ... il serait dommage qu'ils ne se combinent pas. Et je ne vois pas comment faire ça et en même temps gérer l'attaque automatique de manière simple et élégante.

Tant pis donc,autant fermer ce ticket et en ouvrir un d'amélioration pour "filtrer" les attaques avec "--si" dans la liste d'actions.
