### ISSUE TITLE
Feinte du barde

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#277]
@Ulty le 12/3 tu faisais un update sur la Feinte du Barde pour que les bonus ne s'appliquent que sur les attaques au contact. Je te l'avoue, mon Barde en est très frustré. D'ailleurs, je t'ai vu répondre l'inverse sur le forum. https://www.black-book-editions.fr/forums.php?topic_id=4800&nbp=339&nop=293 . Oserais-je me permettre de lever cette restriction (ligne 8076) ?

**Comment by Ulty** [comment]
Effectivement. C'est un résultat d'adaptation des règles de ma part, désolé. J'ai commencé par trouver la feinte trop faible, et j'utilise donc le bonus proposé dans Vengeance (+10 au lieu de +5). Ensuite, j'ai décidé d'augmenter le bonus aux dégâts en fonction du niveau (juste pour un profil hybride que j'ai un peu adapté, le duelliste). Et maintenant, sans vraiment tester, j'ai eu peur que ce soit trop bourrin cumulé au lancer de couteaux. J'imagine que ton barde fait cette combinaison, du coup, c'est ça ? Il le fait depuis quel niveau ? Est-ce que c'était trop fort au début ? Pas assez maintenant ?

Enfin, de toutes façons, j'ai eu tort, désolé pour les conséquences pour ton joueur. Tu peux remettre ça comme dans les règles, bien sûr. Ou si tu veux, je le fais.

**Comment by Far2Casual** [comment]
Pas besoin d'être désolé, on est un peu dans un cas d'école de RAW (Rules as Written) vs RAI (Rules as Intended). Je ne pense pas non plus que l'auteur, dans une voie qui s'appelle "Voie de l'escrime", avait comme idée de permettre des feintes avec des attaques à distance. Mais en attendant, les règles ne disent pas que ce bonus est limité aux attaques au contact, donc c'est dur de rajouter la limitation a posteriori.

Mon Barde utilise cette tactique depuis le niveau 6, et en réalité ne l'utilise que contre les monstres qui ont une réelle chance de survivre à un tour de combat. Feinte reste une capacité très restrictive : 
1. il faut passer un round à rester à proximité d'un ennemi sans aucun bonus défensif
2. c'est mono cible
3. les dommages ne sont au final augmentés que si les DEUX attaquent touchent d'affilée.

En termes de puissance, certes ça fait un fameux boost quand, lors du second tour, le Barde peut faire son attaque à la rapière ET son lancer de couteau gratuit avec les bonus. Mais franchement il y a bien d'autres capacités qui me donnent plus de fil à tordre que celles-là, et on sait lesquelles. Au final, cette capacité permet au Barde, qui est sinon souvent limités à multiples petits dégâts (rapière, couteaux, attaque sonore), d'avoir une chance de chatouiller des créatures dotées de sérieuses RD (notamment via la voie du colosse). 

A terme, si je devais réécrire cette capacité, je dirais en effet que cette capacité n'est liée qu'aux attaques à la rapière, mais je donnerai par contre un effet immédiat à la feinte, comme un bonus conséquent de DEF face aux attaques de la cible pendant un tour en cas de feinte réussie, par exemple +5 DEF.

**Comment by Ulty** [comment]
Je pense que ça devrait être bon comme ça.
