### ISSUE TITLE
Option blessures graves

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#280]
@Ulty : j'envisage de séparer l'option "blessures graves" en deux options, si tu n'y vois pas d'inconvénient.

1. Blessure grave : si 0 PV, -1 PR. Si plus de PR, blessure grave (= affaibli). Si 0 PV et blessure grave, mort définitive.
2. Dégâts importants : -1 PR si DM > CON+Niveau

La raison pour laquelle j'aimerais faire ça est de me débarasser de la partie 2 tout en gardant le reste activé. Une fois qu'on atteint les géants, les PJs perdent des PR sur quasiment chaque attaque, ce qui n'est à mon avis pas l'objectif de la règle, que je n'aime pas trop.

Serais-tu ok avec ça ?

**Comment by Ulty** [comment]
Bien sûr que je suis d'accord pour une option supplémentaire, pas de soucis.

Je suis un peu étonné que ça te pose problème. J'utilise cette règle avec mon groupe actuel sur Roll20, qui vient de finir les géants (fin du scénario 11), et je n'ai jamais eu de soucis avec ça : les magiciens ou voleurs prennent quasiment toujours un PR quand ils se font toucher par un géant de pierre ou de feu (mais pas systématique pour les collines), et le barbare assez rarement, ce qui me semble pas mal. On parle de grosses baffes de géant, ça me semble normal qu'il y ait des conséquences, non ? En tout cas, même avec cette règle, ça ne les a pas empêché de poutrer du géant. Sauf Unguthoar qu'ils n'ont pas osé affronter.

**Comment by Far2Casual** [comment]
Ce n'est pas forcément vrai, un chevalier avec 14 de con (soit assez standard) perd 1 PR sur un coup de géant de givre lors des scénars 10 et 11 en moyenne (DM moyens : 25.5), ce qui n'est pas cool vu le nombre qu'ils vont en affronter. Ca donne un truc bizarre où les PR, normalement destinés au repos, deviennent une sorte de seconde stats de PV ; mes joueurs ne voient même plus leurs points de récupération comme leur potentiel de guérison naturelle, mais uniquement comme le nombre de fois où ils peuvent prendre un coup de géant avant de mourir.

On perd un outil important du jeu, qui permet aux PJs d'enchaîner les rencontres, et on en fait une sorte de "point de destin" qui ne sont plus là que pour éviter la mort.

La première partie, a contrario, me convient bien. Elle donne une véritable conséquence au fait de tomber à 0 PV, qui est quelque chose qui manque cruellement dans COF sinon. Et elle donne aussi une mort "mécanique" en cas de blessure grave, qui n'existe pas non plus sinon.

**Comment by Ulty** [comment]
On pourrait aussi imaginer changer la formule pour les dégâts importants. C'est assez facile de rajouter un facteur 1.5 quelque part, quand on utilise le script.
