### ISSUE TITLE
Projection ne fonctionne pas en cas d'option de preDmg active

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#281]

**Comment by Far2Casual** [comment]
Le même problème survient pour la capacité Gober par exemple.

**Comment by Ulty** [comment]
Pour Gober, c'est normale, j'ai juste repris ce qui était codé pour projection, sans vraiment y réfléchir.

Le mieux, je pense, c'est de remettre à plat l'utilisation de redo. Il faut définir clairement ce que cette option signifie. Je veux bien m'en occuper, mais ça ne pourra probablement pas être avant lundi ou mardi. J'ai plein de trucs à préparer pour ma prochaine session.

**Comment by Far2Casual** [comment]
T'inquiètes, je regarde.

**Comment by Ulty** [comment]
En fait, cet option redo était utile avant que tu mettes en place le preDmg. Il faut vraiment le re-penser, je crois.

**Comment by Far2Casual** [comment]
J'ai un fix c'est très simple, il faut reset target.effets, comme on reset target.additionalDmg, et ne pas utiliser options.redo dans ce cas-ci. Le fix est mini et ça fonctionne très bien.
Mais j'en profite pour faire deux autres fix : persister le roll de la distance de projection, histoire de ne pas avoir des résultats différents, et le fait qu'undo d'une attaque "gober" ne remet pas le token au bon endroit.

**Comment by Far2Casual** [comment]
Ca n'invalide pas ta réflexion sur la partie "redo" attention, juste que dans ce cas-ci cette option un peu brol on l'utilisait à mauvais escient. Le problème était plutôt que des trucs calculés n'étaient pas reset.
