### ISSUE TITLE
Continuer une attaque fait dépenser une nouvelle fois les ressources

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#286]
Si on fait une attaque qui peut être esquivée / parée / absorbée, etc, les ressources (mana, limites par combat, etc) sont depensées deux fois.

@Far2Casual : en relisant le code, je suis un peu surpris : je pensais qu'en cas de preDmg non résolu, on reprenant l'attaque là où on l'avait laissée, c'est à dire <code>resolvePreDmgOptions</code>. Or je vois qu'on repart de la fonction <code>attack</code> et qu'on recalcule tout (et en particulier on refait dépenser les ressources). Est-ce que je me suis trompé, ou ça a bien été comme ça à un moment ? Si oui, est-ce volontaire, le fait que ce ne soit plus le cas ?

**Comment by Ulty** [comment]
@Far2Casual, sauf si tu connais une bonne raison pour toujours tout recalculer, je vais essayer de faire reprendre à <code>resolvePreDmgOptions</code>. J'attends un peu de savoir ce que tu as à en dire, et je m'y colle.

**Comment by Far2Casual** [comment]
Réponse tardive mais ... il me semble qu'on en avait déjà discuté, et que ça créait des bugs sur certains effets ou capacités qui étaient évalués avant cette partie, et dont les conséquences et/ou les messages entraient en conflit après application de la partie "PreDmg". Par exemple, la détermination des cibles, il faut potentiellement la recalculer si des options comme "Chair à canon" sont activées.

Fondamentalement, ce que tu proposes me paraît sensé, mais je me demande ce qui est le plus simple : résoudre le problème ponctuel (la dépense des ressources) ou bien tous les effets de bord liés à ce changement. Je t'en laisse juge, mais je pense que c'est ça qui faisait qu'on avait pas été jusque là finalement.

**Comment by Far2Casual** [comment]
Cf. https://github.com/Ulty/COFantasy/pull/214 je pense

**Comment by Far2Casual** [comment]
Par contre dans https://github.com/Ulty/COFantasy/pull/284 j'ai fixé certains des effets de bord en forçant la réinitialisation de target.messages, ce qui rend peut-être le redo faisable comme tu l'entends.

**Comment by Ulty** [comment]
Ce n'est pas vraiment une réponse tardive. Merci en tout cas, c'est ce genre d'éléments que je cherchais. Je vais essayer d'y travailler demain.

**Comment by Ulty** [comment]
> Réponse tardive mais ... il me semble qu'on en avait déjà discuté, et que ça créait des bugs sur certains effets ou capacités qui étaient évalués avant cette partie, et dont les conséquences et/ou les messages entraient en conflit après application de la partie "PreDmg". Par exemple, la détermination des cibles, il faut potentiellement la recalculer si des options comme "Chair à canon" sont activées.

Il suffit de choisir de ne recommencer l'attaque à zéro que pour les actions comme "Char à canon", et de recommencer à `resolvePreDmgOptions` pour les autres, ou bien il y a quelque chose que j'ai raté ?

**Comment by Ulty** [comment]
En fait, j'ai l'impression que le problème, c'est qu'un certain nombres d'actions font un `redoEvent` sans faire de `undoEvent` avant. Ou alors on n'est pas sensé faire de `undoEvent`, mais certaines actions le font quand même (comme la rune d'énergie ou l'esquive fatale). Du coup on n'est pas très cohérents : dans le cas où on a fait un `undoEvent`, on ne devrait pas mettre de `options.redo`, non ?

**Comment by Ulty** [comment]
Ça semble marcher sur quelques exemples, mais si tu peux tester aussi de ton côté, ce serait plus sûr. Je laisse l'issue ouverte le temps de voir si tout est résolu.

**Comment by Far2Casual** [comment]
Je teste ça ce week-end et je te dis quoi. J'ai des groupes qui utilisent beaucoup d'options de ce genre (tu prends un chevalier, un forgesort, un barde et un guerrier, c'est pas mal 😄), et je suis sur quelques gros combats que je voudrais préparer où ça va être utile, donc ça tombe bien.

**Comment by Far2Casual** [comment]
Bug que j'ai trouvé : 
- Un monstre fait une attaque de zone.
![image](https://user-images.githubusercontent.com/63196064/119144535-0be70300-ba49-11eb-9eff-a48482769419.png)
- Un des joueurs utilise une Rune de Protection, puis on "continue"
![image](https://user-images.githubusercontent.com/63196064/119144603-1dc8a600-ba49-11eb-8807-8a6d3c2edbc0.png)
**BUG N°1** : on dirait que le message "utilise la Rune de protection apparaît deux fois
- Un des joueurs utilise ensuite une Rune d'énergie pour relancer son jet de dex
![image](https://user-images.githubusercontent.com/63196064/119144722-3b960b00-ba49-11eb-84fb-6cfd489fd683.png)
![image](https://user-images.githubusercontent.com/63196064/119144836-5b2d3380-ba49-11eb-8935-efc4d498ed84.png)
**BUG N°1 (suite)** : cette fois par contre, le message "utilise la Rune de protection" n'apparaît qu'une fois
**BUG N°2** : à ce moment-là, je crois que le script "oublie" la consommation de la Rune de Protection ; l'effet de Protection est bien là, mais la rune ne semble pas utilisée. Sur l'attaque prochaine, elle est à nouveau disponible.
![image](https://user-images.githubusercontent.com/63196064/119144940-75671180-ba49-11eb-92c3-1f36a7f5b21b.png)

**Comment by Far2Casual** [comment]
![image](https://user-images.githubusercontent.com/63196064/119147866-44d4a700-ba4c-11eb-8955-17346b310acc.png)
Probablement que le bouton pour la Rune de Puissance ne devrait pas apparaître au niveau des preDmg.

**Comment by Ulty** [comment]
Effectivement, ce n'est pas encore au point. Je vais essayer de tout revoir, mais je ne peux pas le faire avant mardi. Si tu en as besoin avant, n'hésite pas à changer des choses.

**Comment by Far2Casual** [comment]
Suis désolé, j'ai pas eu le temps ce week-end. Je rapporte un autre bug, suis pas sûr que ça soit 100% lié, mais je l'avais pas avant. A l'utilisation d'Intercepter (capacité du Chevalier), il y a un souci avec le jet d'attaque : 
![image](https://user-images.githubusercontent.com/63196064/119276938-21148b00-bc1d-11eb-841f-e49c1ef38538.png)

**Comment by Far2Casual** [comment]
Petite contribution ici : https://github.com/Ulty/COFantasy/pull/288
Ceci devrait fixer le problème ci-dessus avec Intercepter, et le problème rencontré par Kyr avec l'échec total.

Dans les deux cas, le problème est le suivant : ces deux boutons ont pour effet de reprendre une attaque, d'en changer la cible, et d'en copier les options pour la réexécuter. Problème : dans "options" on stocke les "preDmg" et les "redo", et si ces éléments ne sont pas "nettoyés" lors de la copie des options pour relancer l'attaque, on obtient des comportements anormaux.

Typiquement dans le cas d'Intercepter, les options de PreDmg du joueur précédent s'y trouvent, ce qui fait un truc bizarre.
Et pour le problème de Kyr, puisqu'on tente d'appliquer un echecTotal après un 'exemplaire' de Chevalier, l'options redo se trouvait dans l'attaque et faisait foirer le script, puisqu'en fait les cibles avaient changé.

Bref, les deux soucis illustrent probablement un défaut de conception ; dans le cas où on veut "copier" une attaque pour la réexécuter sur une autre cible, probablement que copier tout "options" n'est pas une grande idée, car on copie de cette manière des trucs qui n'ont pas trop de sens. Quelques idées : 
1. Dans ce type de cas, on est plus précis sur les options qu'on copie, ou bien on "cleane" certaines options (c'est le fix que je t'ai push)
2. Peut-être qu'il faudrait séparer les options d'attaque des choses "calculées" comme preDmg et redo, qui ne devrait pas être copiées automatiquement.

Dis-moi ce que tu en penses. Je n'ai pas encore regardé

**Comment by Far2Casual** [comment]
Pour le reste : 
- **Bug double message** : c'est parce qu'à chaque fois que "resolvePreDmg" est appelé, le message est ajouté à la liste des messages de la cible. Comme tu reprends à cet endroit au lieu du tout début (implem précédente), cette liste n'est pas "vidée" et le message est poussé à nouveau et s'accumule. Si dans mon exemple, cinq joueurs avaient une rune de Protection et qu'ils l'activent tous, le premier aura 5x le message dans sa liste. 
_Suggestion de fix : ne pas ajouter le message au moment où l'option est ajoutée (dans appliquerRuneDeProtection), mais uniquement où les dommages sont résolus, donc plus tard_ 
- **Bug Rune de Puissance** : il s'agit à mon avis d'un petit refactoring à faire dans finaliseDisplay, où il faudrait revoir l'ordre d'évaluation de tous les boutons et commencer par les preDmg, et n'afficher les autres que s'il n'y en a pas.
- **Bug Rune pas utilisée en cas de redo** : la modification de l'attribut de la rune de protection se trouve dans _persoUtiliseRuneProtection_ qui est appelé quand on clique sur le bouton. Le fait est que cela générait avant un évènement séparé qui ne faisait pas partie de l'attaque. En cas d'undo (par exemple une rune d'énergie plus tard comme dans l'exemple), l'évènement qui consommait la rune n'était pas undo, seule l'attaque l'était. Ce n'est plus le cas depuis le changement. Du coup l'attribut de rune est rétabli, mais pas reconsommé à la réexécution car la fonction _persoUtiliseRuneProtection_ n'est pas appelée à nouveau, seule _appliquerRuneDeProtection_ l'est.
Deux possibilités : 
1. Soit la consommation de la rune est mise dans un évènement séparé de l'attaque et n'est pas "undo" en cas de redo de l'attaque ultérieurement.
2. Soit la consommation de la rune doit être faite à chaque fois que l'attaque est faite. Attention dans ce cas à ne pas reproduire le même bug qu'avec le double message ci-dessus.

**Comment by Ulty** [comment]
Merci d'avoir regardé tout ça, ça va bien aider à réparer.

**Comment by Ulty** [comment]
@Far2Casual merci, tu m'as bien mâché le travail ;-) Il vaudrait quand même mieux re-tester pour voir si c'est ok comme ça... En particulier, je n'ai pas encore regardé assez en détail les évitements génériques (absorption au bouclier etc).

**Comment by Far2Casual** [comment]
Avec plaisir, je testerai ça aujourd'hui et demain.

Rien à voir, mais tu devrais vraiment ouvrir un petit Patreon. Je suis sûr que certains aimeraient te remercier pour tout l'effort mis dans ce script ;)

**Comment by Far2Casual** [comment]
Je suis à peu près sûr qu'on peut fermer ça, désolé.
