### ISSUE TITLE
Gestion du mouvement sur montures plus pratique

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#289]
@Far2Casual : je sais que tu utilises pas mal les montures. Comment est-ce que tu te débrouille pour que ce ne soit pas trop pénible ?
Personnellement, je trouve que le choix que j'avais fait de faire descendre de la monture quand on bouge le token du cavalier n'est pas pratique. À moins que tu aies un autre avis, je compte changer le comportement pour que bouger le token bouge la monture avec le token, et qu'il faille une commande pour descendre de cheval. Genre `!cof-en-selle` sans argument, ou alors tout` !cof-en-selle` quand on est sur une monture fait descendre de la monture.

**Comment by Far2Casual** [comment]
En effet mes deux groupes ont un Chevalier avec monture. Ça arrive de temps en temps que ça pose un peu problème, mais je dois avouer que ce n'est pas hyper dérangeant. Mais un bouton monter/descendre de cheval pourrait être bien aussi. Bref, pour moi c'est pas un gros problème, mais ta proposition me va.

**Comment by Far2Casual** [comment]
Bon j'avoue hier ça m'a saoûlé 😅 . Parfois tu veux juste sélectionner le token du cavalier, tu le bouges d'1px, et il descend, c'est saoûlant...

**Comment by Ulty** [comment]
J'ai oublié de mettre le numéro d'issue dans le commit, mais j'ai implémenté ça dans le commit 88c20377d335498410f117612e8fbb7ead904707.
