### ISSUE TITLE
Problème de compatibilité entre getSelected et --token-id

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#29]
Salut @waibcam . L'option --token-id que tu as rajouté donne des effets indésirables en conjonction avec certaines options de sélection. Par exemple, si on sélectionne avec --disque et qu'aucune cible n'est dans le disque, alors le token en argument de --token-id est sélectionné. Je vais regarder ça de plus près...

**Comment by Ulty** [comment]
Le problème, c'est que dans certains cas, le script se comporte différemment quand il n'y a rien de sélectionné.

**Comment by Ulty** [comment]
Il existait déjà l'option --target qui faisait ce que tu voulais, je pense. Dis-moi si ça marche toujours comme tu veux.

**Comment by waibcam** [comment]
Salut,

je regarde ça dès que je peux (ce soit ou demain) !
