### ISSUE TITLE
Initiative

### ISSUE THREAD

**Issue by darktarian** [Ulty/COFantasy#30]
Bonjour,

Mj à CoF j'ai pris l'habitude d'utiliser ce superbe script pour Roll20 ! 
Merci pour sa creation, il est génial.

Par ailleurs, j'ai pris l'habitude de modifer la règle d'init en y ajoutant  +1D6 pour ajouter un peu de hasard.
Serait il possible de créer une seconde macro !cof-init avec la possiblité d'y ajouter un dé ?

Merci

**Comment by Ulty** [comment]
@darktarian : merci pour le commentaire. 
Pour l'initiative variable, je pense qu'il faudrait plus qu'une modification de macro, histoire de rester cohérent quand l'initiative est modifée temporairement. Je crois que le mieux serait d'en faire une option de jeu. Dans ton cas, tu tires le d6 une fois pour tout le combat, ou bien à chaque tour ?

**Comment by Ulty** [comment]
@darktarian : voilà, c'est ajouté. Je compte sur toi pour tester et me dire si il y a des bugs ;-).
