### ISSUE TITLE
!en-selle et montures taille G+

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#33]
Lorsqu'une monture est représentée par un token de taille G ou supérieure (comme un gros destrier qu'on représente en 2x1 ou 2x2), le problème c'est que le token du joueur est plus petit que le token de la monture.

Une fois 'en selle', le joueur va avoir son token représenté sur une partie du token de la monture. A partir de ce moment-là, les monstres situés autour de la monture sont souvent hors de la portée "de mêlée" du token du joueur, et la plupart des attaques le ciblant sont impossibles.

De la même manière, le joueur n'aura pas toujours son jeton directement en contact des adversaires au contact de sa monture, et donc il ne pourra pas porter d'attaque de mêlée sur ceux-ci.

**Comment by Ulty** [comment]
Merci de commencer à regarder ce qui devrait être amélioré. Dans le cas particulier de la monture, je ne suis pas encore sûr que le soucis soit réel. Mais peut-être qu'on n'utilise pas le script dans les mêmes conditions ? Par exemple, je préfère en général éviter la grille, pour pouvoir placer mes tokens où je veux, ce qui permet peut-être plus facilement d'aller attaquer par le flan. Autre point à tester, c'est le type de token utilisé : vue de haut ou médaillon ? Je crois que jusqu'à présent, j'ai toujours utilisé des tokens vus de haut (saus pourtour, avec transparence).

Pour l'historique de l'issue, je rappelle l'utilisation de l'option d'attaque **--allonge**, qui permet de simuler les armes longues, permettant d'attaquer depuis sa (grosse) monture ou d'attaquer un cavalier perché sur une très grande monture.

**Comment by Far2Casual** [comment]
Je t'illuste clairement la chose avec ma situation ; il est vrai que j'utilise grille et des tokens, mais ça ne devrait pas poser un tel souci. Dans la situation ci-dessous, notre brave chevalier elfe monte sur son destrier de guerre.
![situation1](https://user-images.githubusercontent.com/63196064/78578501-ea6c8d00-782f-11ea-8d0c-4748b2aee5fc.JPG)

Il lui sera incapable d'attaquer ou d'être attaqué par le gobelin rouge, alors qu'il n'est jamais que sur un destrier. Régler le token du chevalier pour qu'il soit au milieu de celui du cheval n'aide au final pas beaucoup ; dans le cas-ci-dessous, il ne peut attaquer ni être attaqué par aucun gobelin.
![situation2](https://user-images.githubusercontent.com/63196064/78578678-20117600-7830-11ea-8ec6-83d6d01f8ddd.JPG)

J'entends l'idée de l'allonge, du manque de portée etc, mais on diverge déjà d'un standard D&D, et ça me paraît une complexification inutile surtout pour CO Fantasy qui veut simplifier.

Je propose le fix suivant : si un monstre est à portée de la monture, il l'est aussi du cavalier et réciproquement. Bref, si le cavalier est "en selle", la portée des attaques portées par lui et vers lui sont vérifiées en fonction de sa monture. Cela résoudra tous les cas sauf ceux où la monture est plus petite que le cavalier, ce qui je pense n'arrivera jamais.

Qu'en penses-tu ?

**Comment by Ulty** [comment]
Je vois le problème, en effet. Je ne pensais pas que tu utilisais un si gros token pour un cheval, mais en y réfléchissant, je crois que je comprends pourquoi. Si un MJ veut simuler la difficulté à atteindre un cavalier sur sa monture, il pourra toujours faire ça au jugé. Ok pour que tu implémentes ta solution, donc.

**Comment by Ulty** [comment]
Résolu, je pense.
