### ISSUE TITLE
Voie du tueur rang 2 & 3

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#41]
Pour le support du rang 2 & 3 de la voie du tueur : 

2. A moins que je me trompe, il manque la possibilité de pouvoir effectuer à la demande un jet opposé entre deux tokens. Que suggères-tu ?
a. On implémente une simple "Ability" qui demande d'encoder à la main la difficulté du jet ? (ce que j'ai fait pour l'instant)
b. On implémente une commande spécifique pour ceci, par exemple #cof-tueur-disparition-test qui permet de sélectionner une cible et qui lance automatiquement le jet
c. On implémente un système générique de jet opposé, !cof-jet-oppose qui prend en paramètre deux tokens et deux valuers
d. On rajoute à !cof-jet des arguments optionnels permettant d'opposer le jet 

3. Cette partie-là est assez simple, il suffit de rajouter `--if etatCible surpris --etat mort --save CON 15 --endif` à l'ability créée pour l'Attaque Mortelle (rang 1). Par contre, je me rends compte que conférer l'état mort ne met pas les PV à 0. Que penses-tu de modifier `setState` pour que si on donne l'état mort, on mette les PV à 0 via `updateCurrentBar` ?

**Comment by Ulty** [comment]
Pour le rang 2, je prends ça comme une condition pour que l'attaque soit une sournoise. Je rajouterais donc une option plutôt à `!cof-attack`. Soit un argument supplémentaire à `--sournoise`, soit mieux encore une extention des conditions, de façon à faire un résultat en fonction du résultat d'un test opposé, et on ferait un truc du genre `--if testoppose discrétion SAG --sournoise 4 --bonusAttaque 5 --endif`. L'inconvénient de cette approche serait la difficulté à gérer la possibilité pour la cible de dépenser un point de chance. Mais ça me semble jouable.

Pour le rang 3, je suis d'accord avec toi, il faudrait modifier le `setState`.

**Comment by Far2Casual** [comment]
> Pour le rang 2, je prends ça comme une condition pour que l'attaque soit une sournoise. Je rajouterais donc une option plutôt à `!cof-attack`. Soit un argument supplémentaire à `--sournoise`, soit mieux encore une extention des conditions, de façon à faire un résultat en fonction du résultat d'un test opposé, et on ferait un truc du genre `--if testoppose discrétion SAG --sournoise 4 --bonusAttaque 5 --endif`. L'inconvénient de cette approche serait la difficulté à gérer la possibilité pour la cible de dépenser un point de chance. Mais ça me semble jouable.

Alors en réalité Discrétion ne requiert qu'un test de l'attaquant (discrétion vs SAG de la cible), il n'y a donc pas de test opposé nécessaire.

Pour le reste, hé bien j'ai regardé pour faire ça, et ça m'a forcé à rentrer dans les ITE, les rolls etc. Et ça ne me semble pas si simple. J'ai une implem de base, mais je suis confronté à 3 obstacles majeurs :

1. C'est la première fois qu'on donne une compétence sans avoir l'attribut explicitement donné en paramètre également ; est-ce la bonne syntaxe du coup ? Il faut sinon rajouter une nouvelle fonction pour faire cela, genre "getAttributeByCompName".
2. D'après ce que j'en ai compris, les ITE sont évalués dans atkDealDmg, soit après qu'on ait décidé si on touche ou pas. --bonusAttaque dans un ITE n'a actuellement aucun effet.
3. S'il faut inclure un vrai jet de compétence complet (donc en asynchrone) pour gérer les points de chance, alors il faut complètement refactoriser evalITE et atkDealDmg qui ne sont pas prévus pour travailler de la sorte. Mais là j'avoue que j'atteins mes limites actuelles de compréhension des jets asynchrones.

**Comment by Ulty** [comment]
Non, la capacité dit bien qu'il s'agit d'un test opposé, il faut donc faire lancer un jet par l'attaquant et un par la cible.

Sinon, effectivement, c'est peut-être trop ambitieux de modifier les ITE pour ça. Ça laisse 2 possibilités réalistes, je pense

- un option d'attaque dédiée, genre `--disparition`, qui fasse les jets à la façon de la capacité charge de la voie du cogneur (option `--pietine`)
- ou alors une fonction générique de test opposé, peut-être en étendant !cof-jet, que le MJ peut utiliser pour savoir si il doit lancer une attaque mortelle ou pas.

**Comment by Ulty** [comment]
Je propose qu'on ferme cette issue, ça me semble tout à fait bien. Pour les points de chance, ce n'est pas le seul cas où il manque une implémentation. J'ouvrirai une issue dédiée.

**Comment by Far2Casual** [comment]
Ouaip, c'est globalement réglé, à l'exception de la partie chance mais qui est, je suis tout à fait d'accord, une issue séparée concernant les tests opposés et la chance.

C'était très intéressant pour moi ça m'a permis de rentrer en profondeur dans certaines parties du script, les ITE, parseAttack, attack, les compétences, les jets asynchrones, etc.
