### ISSUE TITLE
Attaque en meute du gobelin

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#42]
Il n'y a pour l'instant pas de support pour l'_Attaque en meute_ spéciale des gobelins.

Proposition : ajouter une option --meuteGobelin aux attaques des gobelins. 
- Si une attaque avec cette option vise un personnage sans l'attribut "meuteGobelin", pas de bonus mais création de l'attribut.
- Si une attaque avec cette option vise un personnage avec l'attribut "meuteGobelin", bonus de +2 à l'attaque.
- Retrait de l'attribut "meuteGobelin" à la fin de chaque tour.

**Comment by Ulty** [comment]
Normalement, l'_Attaque en meute_ donne un bonus de +2 à tous les gobelins qui attaquent la même cible pendant un tour, y-compris le premier d'entre eux.
