### ISSUE TITLE
Option d'attaque pour jouer un son

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#45]
Ce serait sympa d'avoir une option d'attaque pour jouer un son si l'attaque réussit, voire un autre son si l'attaque rate.

**Comment by MathieuGaloseau** [comment]
Je vient de te faire un Pull request qui ajoute des Gif en fonction des attaques, je vais voir si je peu en plus gérer les son :-)

**Comment by Ulty** [comment]
Ce serait bien cool ! Je n'ai pas encore regardé comment fonctionnait l'interface de l'API avec le jukebox Roll20, comme ça je n'aurai pas à le faire :)

**Comment by Ulty** [comment]
Je crois que ça marche bien. Encore merci, Mathieu !
