### ISSUE TITLE
Support de l'épieu

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#47]
L'épieu confère les avantages suivants : 
- +2 en DEF contre les attaques naturelles
- 2D6 DM contre les adversaires sans armure manufactuée

Le script pourrait gérer la partie 1, lorsqu'on dégaine l'épieu on gagnerait un bonus circonstanciel de +2 DEF contre les attaques naturelles

Pour la partie 2, COF de base ne gérant pas lui-même l'info explicite de l'armure dans les profils des monstre, je ne vois pas comment l'automatiser. Dès lors, j'aurais simplement tendance à inclure un ?{Cible avec armure ?[Oui,&nbsp;|Non,--plus [[1d6]]} dans l'attaque.

**Comment by Ulty** [comment]
Pour l'attaque sur les PNJs, on pourrait aussi utiliser `estAnimal` en première approximation. Et sinon ajouter un attribut `enArmure` pour affiner. Ça pourrait aussi être une case à cocher sur la fiche de PNJs, à voir si je peux caser ça... Peut-être un menu déroulant entre sans armure, en armure, bouclier et armure + bouclier. Qu'est-ce qui te semblerait le mieux ?

**Comment by Far2Casual** [comment]
J'aime bien la piste sur la fiche de PNJ. Peut-être simplement deux cases à cocher pour armure et bouclier, car ça serait similaire à ce qui se passe sur la fiche des PJ.
Cela permettrait d'implémenter facilement le bonus aux dégâts de l'épieu si pas d'armure, et les bonus à la touche des fléaux contre les boucliers par exemple.

**Comment by Ulty** [comment]
Une idée de l'endroit où mettre ça sur la fiche PNJ ?

**Comment by Far2Casual** [comment]
Clairement le plus logique ce serait de mettre ça autour / dans la partie "DEF". Mais ça nécessite de bouger pas mal de trucs. Si ça te fait pas peur, pourquoi ne pas refactoriser un peu la fiche avec :
DEF [   ]      Armure [X]     Bouclier [X]          RD[         ]
PV max [    ]    PV actuels [         ]     DM temp [          ]
Init [         ]    Jets  [           ]

**Comment by Ulty** [comment]
Oui, c'est une idée. Je vais y réfléchir. De toutes façons, ça ne sera pas en ligne avant la semaine prochaine.

**Comment by Ulty** [comment]
Il me reste juste à faire la synchronisation automatique entre les attributs PNJs et PJs pour que le script n'ai pas à se soucier de savoir si on tape sur un PJ et PNJ, et on pourra implementer ça.

**Comment by Ulty** [comment]
Je dirais que c'est réglé.
