### ISSUE TITLE
Bug avec Asphyxie

### ISSUE THREAD

**Issue by waibcam** [Ulty/COFantasy#5]
Salut Ulti,

Il semble y avoir un souci d'affichage avec Asphyxie. C'est assez facile à reproduire : [https://www.youtube.com/watch?v=v3kKmSupaJo](https://www.youtube.com/watch?v=v3kKmSupaJo)

J'utilise cette version : https://github.com/Ulty/COFantasy/commit/6b5525a38de0d0524777ad9c693e3521acb127a5

Les dégâts semblent être comptabilisés qu'une fois mais l'affichage est triple.
Je pense que cela vient du fait qu'il y a 3 "tokens"  (Orque 1, Orque 2 et Osque 3) du même personnage Orque.

Pour info, Flèche enflammée (qui est sur un principe équivalent) fonctionne correctement.

C'est pas critique mais je tenais à le remonter.

**Comment by Ulty** [comment]
Tout fonctionne chez moi. La seule façon que j'ai trouvé de reproduire ce que tu me montres, c'est d'avoir plusieurs tokens non-liés avec le même nom. 

Dans ton cas, je dirais que tu as un autre "Orque 2" quelque part sur une autre map.

Si tu utilises TokenNameNumber, ça ne devrait jamais arriver, sauf copié-collé du token.

Dans le cas où ça arrive, le script n'a aucun moyen de savoir de quel "Orque 2" il peut s'agir. Si on en choisi un, il se peut que ce soit le mauvais, et dans ce cas l'orque asphyxié ne perdra pas de PV. Pour les tokens liés, ce n'est pas un soucis, mais là, je ne vois pas trop comment empêcher ça.

**Comment by waibcam** [comment]
Mais  oui ! C'était ça :) Un vieux copier/coller pendant une session et hop !
Merci ! Je ferme le sujet.
