### ISSUE TITLE
Étendre l'utilisation des points de chance

### ISSUE THREAD

**Issue by Ulty** [Ulty/COFantasy#53]
La possibilité d'utiliser des points de chance devrait être offerte à chaque fois d'un d20 est lancé par un joueur. Il reste plein de cas à implémenter, comme les sauvegardes dans les attaques, par exemple.

**Comment by Far2Casual** [comment]
Ensuite si tu valides mon implem de #119, ça sera beaucoup plus simple de rajouter les options de chance dans les jets de sauvegarde des attaques puisque les jets seront déjà persistés.
Ca devrait mettre les bases pour être étendus aux autres cas, style attaque opposée, cof-dmg, etc.

**Comment by Far2Casual** [comment]
Salut Ulti, que penses-tu de ceci ?
![image](https://user-images.githubusercontent.com/63196064/98264731-81492580-1f88-11eb-99e7-a41d7cd6abb7.png)

Ensuite le joueur clique sur "Chance" à l'intérieur : 
![image](https://user-images.githubusercontent.com/63196064/98264824-9b830380-1f88-11eb-99c1-b01e6228e44b.png)

**Comment by Ulty** [comment]
Ha oui, ça a l'air bien ! 
Il vaudrait peut-être mieux attendre un peu : je suis en train de coder l'utilisation des points de chance pour les esquives et autres, et il faudra aussi que ça interagisse correctement avec les runes de protection ou autres.

**Comment by Far2Casual** [comment]
Ok je m'interromps là pour l'instant. Je ne l'ai pour l'instant implémenté que dans la partie etatsAvecSave, mais j'ai déjà mis les bases pour des boutons de chance sur des rolls spécifiques d'action?

Si je comprends bien ce que tu veux dire, a priori on ne touche pas forcément aux mêmes parties donc le merge devrait bien se passer. J'attends néanmoins ton go pour continuer.

**Comment by Ulty** [comment]
C'est ok pour moi, tu peux reprendre le développement. J'ai hâte de voir ça !

**Comment by Ulty** [comment]
J'ai l'impression qu'il y a un bug dans ce commit : dans la fonction `evalITE`,  ligne 5692, tu utilises un variable `rollId` qui n'a pas l'air défini.

**Comment by Far2Casual** [comment]
J'ai tenté beaucoup de choses et j'ai fait un clean à la fin, visiblement je suis remonté trop en arrière. Fix dans le MR.

**Comment by Far2Casual** [comment]
Je reprends ici mon analyse de la suite de cette story car il serait tout à fait possible d'étendre encore l'utilisation des PC à tous les cas où des jets de sauvegardes sont demandés (en dehors donc des attaques), mais il faut se plonger dans ces évènements car ils ne permettent pas tous un undo/redo automatique, l'information les concernant étant parfois incomplète.

Ne sont pour l'instant pas supportés à cause de cela : 
- les jets de sauvegardes pour dommages partiels (évènement cof-dmg)
- les effets temporaires (évènement cof-effet-temp) 
- les sauvegardes journalières contre un effet (évènement cof-nuit)
- les sauvegardes "nouveau tour) (évènement cof-next-turn)
- l'interface set-state (évènement cof-set-state)
- dégaîner (évènement cof-degainer)
- la résistance à l'alcool (évènement cof-boire-alcool)
- tueur fantasmagorique (évènement cof-tueur-fantasmagorique)

**Comment by Far2Casual** [comment]
J'ai une question pour toi @Ulty. Je suis en train de m'attaquer aux autres types d'évènements, et je commence par cof-dmg puisque c'est déjà à moitié fait.

J'ai refactoré le traitement de !cof-dmg à la manière de !cof-attack, afin d'avoir une fonction qui traite le parsing des options et une fonction d'exécution. Le but est évidemment de pouvoir faire un "redo" en utilisant juste la fonction d'exécution.

Maintenant, je dois modifier la structure de l'évènement stocké dans l'historique afin de pouvoir le reproduire, et là je m'interroge. As-tu une idée précise ou une opinion sur comment structurer l'évènement de cof-dmg ? Dois-je inclure une partie "action" avec les rolls dedans comme pour une attaque, ou bien je fais une autre structure ?

**Comment by Ulty** [comment]
Je pense qu'il vaut mieux utiliser la même structure globale pour tous les événements : donc une partie "action" avec les rolls.

**Comment by Far2Casual** [comment]
Comme ceci ?
![image](https://user-images.githubusercontent.com/63196064/98960867-389fe800-2505-11eb-9c5c-ef817c1b1d5f.png)

**Comment by Ulty** [comment]
Oui, ça me semble bien.

**Comment by Ulty** [comment]
J'ai l'impression qu'il y a un bug depuis le dernier refactoring : ligne 14172, on appelle la fonction chanceCombat, qui n'existe plus.

**Comment by Ulty** [comment]
Ligne 16454, tu as aussi une affectation au moins inutile, je n'ai pas regardé en détail si c'est un bug
`              evt = originalEvt;
`
`evt` n'est ni défini, ni utilisé.

**Comment by Far2Casual** [comment]
> J'ai l'impression qu'il y a un bug depuis le dernier refactoring : ligne 14172, on appelle la fonction chanceCombat, qui n'existe plus.

Très juste, mais ce morceau de code fait partie de la fonction "chance()", dont la seule utilisation provient d'une commande cof-chance indiquée dans le code comme "deprecated". Je ne vois pas à quoi elle sert, tu as une idée ? On pourrait peut-être tout simplement supprimer le code et le support de la commande.

**Comment by Ulty** [comment]
Ça servait pour les cas non gérés par le script. Probablement plus utile pour ça. Ça servait aussi à diminuer les points de chance, mais je pense qu'on peut s'en passer. Je vais supprimer cette fonction.

**Comment by Far2Casual** [comment]
> Ligne 16454, tu as aussi une affectation au moins inutile, je n'ai pas regardé en détail si c'est un bug
> ` evt = originalEvt;`
> `evt` n'est ni défini, ni utilisé.

Ca par contre c'est bien vu, le code lui-même je ne l'ai pas écrit, mais le refactoring l'a peut-être cassé. Il va falloir que j'investigue. Tu as une idée à quoi sert l'option "waitingForAoE" ?

**Comment by Ulty** [comment]
> > Ligne 16454, tu as aussi une affectation au moins inutile, je n'ai pas regardé en détail si c'est un bug
> > ` evt = originalEvt;`
> > `evt` n'est ni défini, ni utilisé.
> 
> Ca par contre c'est bien vu, le code lui-même je ne l'ai pas écrit, mais le refactoring l'a peut-être cassé. Il va falloir que j'investigue. Tu as une idée à quoi sert l'option "waitingForAoE" ?

Oui, ça sert pour les cas où la forme des AOE n'est pas  évidente, et donc on laisse le MJ sélectionner les cibles avant d'appliquer l'effet. En pratique, je crois qu'on n'en a besoin que pour la destruction des morts-vivants. Je pourrais peut-être un jour améliorer cette capacité et me servir des lignes sur le layer dynamic lighting.

**Comment by Ulty** [comment]
Un autre bug, je crois : sendPlayer attend soit un message (venant de l'API, avec un champ `who`), soit un nom de joueur. J'ai l'impression que ça ne fait rien de sensé avec un playerId (comme ligne 16532).

**Comment by Far2Casual** [comment]
Désolé pour tous ces effets de bord en tout cas.

**Comment by Ulty** [comment]
> Désolé pour tous ces effets de bord en tout cas.

C'est à peu près inévitable dès que tu fais des changements importants. En tout cas, je serais mal placé de t'en vouloir, vu les bugs que je laisse régulièrement dans le code !

**Comment by Far2Casual** [comment]
@Ulty alors j'ai regardé Destruction des Morts-Vivants, mais j'avoue que je ne vois toujours pas très bien quel est le lien. La ligne 16454 dont tu parlais, elle est liée au traitement d'une option nommée "once". Le truc, c'est que je ne vois nulle part, ni dans le script, ni dans la documentation, la moindre utilisation de cette option.

Je viens de tester la Destruction des Morts-Vivants et avec ton fix sur sendPlayer, ça fonctionne bien. Du coup je me demande ; s'agit-il aussi d'un truc déprécié ?

**Comment by Ulty** [comment]
@Far2Casual : ça se pourrait. Je vais regarder.

**Comment by Ulty** [comment]
Non, en fait je crois que c'est important pour le undo : undo doit enlever à la fois les dégâts et les ressources utilisées dans le jet de sagesse (genre fortifiant). Je vais essayer de réparer ça.

Pour le once, je n'ai pas encore regardé.

**Comment by Far2Casual** [comment]
Je pense que je vois ce que tu veux dire, c'est tout à fait jouable : le parse de once recherche l'event et le rajoute dans une option (par exemple, options.originalEvt), et dans dmgDirects on fait un if qui au lieu de créer un nouvel event, le reprend si l'option est présente.

Par contre je vois pas comment ça fonctionnait même avant refactoring, puisque l'option n'est pas utilisée ?

**Comment by Ulty** [comment]
Si elle est utilisée, justement dans la destruction des morts-vivants. Je ne vois pas le lien avec `once`, en revanche.

**Comment by Far2Casual** [comment]
Ok je crois que j'avance. Dans le refactoring de dmgDirects, j'ai appliqué à la même simplification que tu avais fait ailleurs en faisant un addEvent() beaucoup plus tôt. Or en remontant dans le code, j'ai vu qu'avant la sous-méthode finalDisplay faisant ceci : 

`if (someDmgDone) {
                sendChat("", endFramedDisplay(display));
                if (evt.affectes || evt.attributes) {
                  if (evt.waitingForAoe) {
                    delete evt.waitingForAoe;
                  } else {
                    addEvent(evt);
                  }
                }
              }`

Je n'ai as repris la partie waitingForAoe. Par contre je n'explique toujours pas le rapport avec l'option once qui même il y a deux semaines n'était utilisée nulle part dans le code.

**Comment by Far2Casual** [comment]
@Ulty : ok j'ai retracé la chose, tu as fait un commit le 27/5 sur Destruction des Morts-Vivants et tu as retiré l'utilisation de l'option --once à ce moment-là.

**Comment by Ulty** [comment]
L'option --once était utilisée à l'origine pour éviter qu'un joueur utilise plus d'une fois un bouton donné.
Dans le cas de la destruction de morts-vivants, je me souviens que je l'ai enlevé pour que le MJ puisse sélectionner les morts-vivants en plusieurs fois.

**Comment by Ulty** [comment]
J'ai pas eu le temps de tester. J'ai aussi enlevé le `once` qui n'était plus utilisé.

**Comment by Far2Casual** [comment]
Ca fonctionne avec le micro commit que je te propose Merge Request. J'ai aussi testé avec ton histoire de fortifiant, et c'est bon.

Par contre, "ça fonctionne" mais ça pourrait poser problème à terme car c'est une utilisation de cof-dmg qui fait semblant de ne pas l'être, notamment parce que l'event n'est justement pas identifié comme étant un évènement de type "dmgDirect". 

Si les dommages étaient soumis à une pSave, les boutons Chance qui y seraient placés ne fonctionneraient pas car on essaie d'appliquer de la Chance à un évènement non supporté. C'est vraiment pas grave car 
1. Ca ne surviendra jamais (en tout cas dans l'état actuel du script)
2. Je peux envisager de supporter ça dans la suite de l'implem de ce ticket.

**Comment by Ulty** [comment]
je suis tombé sur un bug hier soir : le script plante maintenant si on utilise la tempête de mana avec `!cof-effet-temp`. Je vais regarder ça ce matin.

**Comment by Far2Casual** [comment]
C'était vraiment un gros refactoring effetTemp, j'aurais du prendre plus de temps pour tout retester. Encore désolé pour le bug.

**Comment by Ulty** [comment]
Tu peux me dire si ça marche, maintenant, la hâte ?

**Comment by Far2Casual** [comment]
Impec !

**Comment by Far2Casual** [comment]
J'ai remarqué une régression avec les dernières versions, les boutons de Chance sur les jets de sauvegarde d'attaques ne fonctionnent plus. Je vais regarder.

**Comment by Far2Casual** [comment]
@Ulty : question pour toi, tu connais mieux l'API roll20 que moi. Pour implémenter le PC sur saveParTour, j'ai besoin de pouvoir refaire un "nextTurn". Mais si j'appelle simplement nextTurn(Campaign()) après avoir fait l'undoEvent, ça ne fait rien. Tu as une idée ?

**Comment by Ulty** [comment]
Il y a vraiment des cas où il y a besoin de PC pour `!cof-degainer` ?

**Comment by Far2Casual** [comment]
L'option de faire une save est là en tout cas. Et cette option est directement utilisée dans notre table d'échec critique (résultat #3, arme de contact).

On arrive au bout de tous les cas de save(). Une fois que ça sera fait, je ferai une passe de refactoring car puisque ça sera appelé partout, on pourra factoriser beaucoup de choses (l'ajout des rolls, le redo, etc).

Ca me permet de demander : je vais fait boire-alcool, mais je remarque qu'il y a aussi un truc "vapeurs-éthyliques". Il n'y a aucune doc là-dessus et ce n'est appelé nulle part. C'est un truc à toi ?

**Comment by Ulty** [comment]
> Ca me permet de demander : je vais fait boire-alcool, mais je remarque qu'il y a aussi un truc "vapeurs-éthyliques". Il n'y a aucune doc là-dessus et ce n'est appelé nulle part. C'est un truc à toi ?

Oui, j'ai eu un joueur qui préférait lancer des fioles de vapeurs éthyliques plutôt que des feux grégeois. Un concept de personnage pacifique.

**Comment by Far2Casual** [comment]
D'accord ben écoute à moins que tu me dises que c'est obsolète et plus utilisé, je ferai le petit refactoring PC aussi. Comme je dis une fois que tout est fait, je ferai une pause "nettoyage et refactoring" puisque tous les cas de save seront supportés. Comme le système générique est en place, je pense que je pourrai aussi facilement faire passer les capacités "petit veinard" et "intervention divine" dans le même système, sans devoir tout copier/coller.

**Comment by Ulty** [comment]
C'est toujours utilisé. En tout cas on a une partie en cours avec ce perso, même si c'est un peu en pause depuis 2 mois.

Bref, ton plan me paraît excellent. Encore merci.

**Comment by Ulty** [comment]
Merci pour ce super boulot !!

Puisque tu es encore un peu dans ce code, est-ce que tu pourrais aussi rajouter la possibilité d'utiliser les points de chance pour la destruction des morts-vivants (jet de sagesse du prêtre) ?

En tout cas, un joyeux Noël à toi !

**Comment by Far2Casual** [comment]
J'ai vite regardé et ouais, en gros destruction des Morts Vivants utilise testCaractéristique. J'ai commencé par save() parce qu'il y avait déjà beaucoup d'usage, mais save() utilise lui-même testCaractéristique(). La suite logique de cette story est effectivement de remonter jusqu'à testCaractéristique() pour l'ajout automatique de toutes les boutons de redo().

Voici la nouvelle "Todo list" :
- [ ] EchapperEnveloppement
- [ ] Rage du Berserker
- [ ] Destruction des Morts Vivants
- [ ] Nature Nourricière
- [ ] Surprise
- [ ] Récupération
- [ ] Sommeil
- [ ] Tour de Force
- [ ] Enduire de Poison
- [ ] Changement de Tour (Vapeurs éthyliques)
- [ ] Arme secrète (barde)
- [ ] doSaveState
- [ ] evalSanctuaire
- [ ] jetPerso
- [ ] peurOneToken
- [ ] save

 mais ça sera pour l'année prochaine ;)

**Comment by Ulty** [comment]
Ouch, effectivement, il reste du boulot !

**Comment by Far2Casual** [comment]
Reste plus qu'à refactoriser toutes les commandes ci-dessus pour supporter l'undo/redo, et on est bons ;)

**Comment by Ulty** [comment]
Bravo !

**Comment by Far2Casual** [comment]
Yo @Ulty avec un récent commit tu as changé le "type" de l'évent "echapperEnveloppement" en cas d'étreinte : 
`type: (etreinte) ? "Tentative de libération d'étreinte" : "echapperEnveloppement",`
En faisant ça, ça retire le support de redoEvent() et donc du bouton Chance. Est-ce volontaire, ou bien je peux corriger ?

**Comment by Ulty** [comment]
je n'avais pas vu que tu utilisais dirctement le type dans le `redoEvent`. Je voulais juste corriger le problème de la variable `evt `utilisée là où elle n'existait plus. Tu peux corriger @Far2Casual , merci !

**Comment by Far2Casual** [comment]
Ca roule, pas de souci.
Je documente ça ici aussi parce que c'est lié, mais depuis peu j'ai des doublons dans les explications d'attaque en cas d'utilisation d'undo/redo. C'est pas grave mais c'est moche.
![image](https://user-images.githubusercontent.com/63196064/103633621-493d6f00-4f46-11eb-9ef8-0d14db36ecaf.png)
![image](https://user-images.githubusercontent.com/63196064/103633653-535f6d80-4f46-11eb-87d1-614d924e543a.png)

**Comment by Ulty** [comment]
Effectivement, il va falloir régler ça. Tu veux que je m'en charge ?

**Comment by Far2Casual** [comment]
Heuuu, si tu veux, je pense pas pouvoir faire beaucoup cette semaine malheureusement.

**Comment by Ulty** [comment]
Je vais m'occuper du texte en double.
En revanche on a un autre soucis que je ne vais pas regarder tout de suite : il y a des problèmes en cas d'attaque avec save (genre `--etat affaibli --save CON 15`) sur un personnage avec le moyen d'éviter l'attaque (comme une esquive acrobatique). dans ce cas, si l'attaque touche et qu'on choisit de continuer, puis le save rate et on choisit d'utiliser un point de chance, le point de chance est dépensé, mais on se retrouve à nouveau au choix d'utiliser l'esquive. Et si on continue, on fait un nouveau save.

**Comment by Far2Casual** [comment]
J'ai fait le test, et le jet du save est bien persisté donc ça va, mais par contre je vois que le jet de l'esquive est effectivement relancé. C'est bien à ça que tu fais référence ? Si c'est le cas, je peux m'en occuper. Il faudrait que les options de `predmg` soient persistés, ça serait beaucoup plus simple.

**Comment by Far2Casual** [comment]
Pour doc : 
![image](https://user-images.githubusercontent.com/63196064/103645335-1c925300-4f58-11eb-87a6-73bd032c37e5.png)
![image](https://user-images.githubusercontent.com/63196064/103645357-274ce800-4f58-11eb-910e-e76bd8bb6fb9.png)
![image](https://user-images.githubusercontent.com/63196064/103645395-3469d700-4f58-11eb-9e4f-c3ebd30e78a5.png)
![image](https://user-images.githubusercontent.com/63196064/103645426-4186c600-4f58-11eb-804b-241c66059b6b.png)
![image](https://user-images.githubusercontent.com/63196064/103645469-506d7880-4f58-11eb-8dd5-8af9dbf12741.png)

**Comment by Far2Casual** [comment]
Ha bah j'ai trouvé, le système de PC et de persistance de rolls sur evitementGenerique est pas du tout intégré au reste. D'ailleurs je remarque que ça n'utilise pas du tout testCaracteristique, et c'est pour ça que je suis passé complètement à côté.
Il y a une raison pour laquelle on n'utilise pas testCaractéristique ? Parce que si je refactore en l'utilisant, ça va être magique, tout fonctionnera d'un coup.

**Comment by Ulty** [comment]
2 points : 

1. Je faisais référence au jet du save. Dans mon cas, c'était en appuyant sur **Continuer** à chaque fois
2. Je ne sais pas trop exactement à quel test tu fais référence pour le jet. Si c'est le jet pour l'esquive acrobatique, ça n'utilise pas `testCaracteristique` parce que c'est un test d'attaque, pas un test de caractéristique. Mais je me trompe peut-être de test ?

**Comment by Far2Casual** [comment]
Tu as raison pour le test, c'est effectivement un test d'attaque. C'est noté.
Par contre pour le save, je n'ai pas le comportement. Exemple ici : 

1. L'Ettin attaque 
![image](https://user-images.githubusercontent.com/63196064/103654007-9da41700-4f65-11eb-8e93-0c28d2ba7000.png)
2. Gerulf "continue" 
![image](https://user-images.githubusercontent.com/63196064/103654061-b44a6e00-4f65-11eb-8cf7-319fe5f129d3.png)
3. Il utilise sa Rune d'énergie pour relancer le jet de sauvegarde du premier effet, car le second est réussi. Le jet de touche est bien identique. 
![image](https://user-images.githubusercontent.com/63196064/103654179-d47a2d00-4f65-11eb-95d5-6a153c66c619.png)
4. Il "continue" à nouveau. Le jet de dommage est le même, le jet de sauvegarde du second effet est bien le même aussi, seul le premier jet est relancé grâce à la rune. 
![image](https://user-images.githubusercontent.com/63196064/103654340-08ede900-4f66-11eb-96b9-fea14963c53d.png)

**Comment by Far2Casual** [comment]
L'amélioration qui devrait avoir lieu c'est que le script devrait mémoriser les options de preDmg utilisées ou non et les refaire à l'identique. Par contre et j'ai regardé c'est à nouveau un gros refactoring.

Par contre si tu reprends l'exemple du dessus, si tu fais la même chose mais en utilisant l'esquive Acrobatique, là le jet d'attaque en question n'est pas persisté et est relancé, ce qui est en effet un bug. Ca je pense pouvoir le corriger assez facilement en persistant le roll correctement.

**Comment by Ulty** [comment]
Tu as raison, ça a l'air de marcher, maintenant. J'ai dû me tromper.

**Comment by Far2Casual** [comment]
Je vais faire une issue séparée pour le redo automatique des options de preDmg. Simplement parce que c'est une grosse story de refactoring, et que j'ai envie de clôturer ce qu'il y a au-dessus avant ;)

**Comment by Far2Casual** [comment]
J'ai fini tous les cas de testCaracteristique ! :D. Je te ferai un PR avec ce qui reste. 

Par contre, ton bugfix m'a fait trouver un gros bug dans le redo d'attaques et les éventuels dommages additionnels. Ils sont à la fois persistés et recalculés, cela fait parfois des erreurs de calcul, et parfois tout simplement planter le script.

**Comment by Far2Casual** [comment]
J'ai investigué et le problème est en effet celui-là, options.additionalDmg est un simple tableau dans lequel on ajoute des dommages additionnels au fur et à mesure qu'on les trouve. Du coup si on refait les attaques, les dommages sont ajoutés à chaque fois.

Ca ne se produit pas sur les additionalDmg liés à la cible, car ceux-ci sont reset à chaque fois qu'on attaque, donc un reDo les reset également. Le problème est qu'on met dans le même array ce qui provient du parsing et ce qui est résolu au fil de l'eau.

Attention un simple `if(!options.redo)` n'est pas une bonne option car un redo peut changer complètement le résultat et donc il faut pouvoir recalculer des parties. 

La solution me paraît évidente : à la résolution, tous les "additionalDmg" qui ne proviennent pas de la commande ne doivent pas être ajoutés à options.additionalDmg et recalculés complètement à chaque appel d'action, tout comme target.additionalDmg

**Comment by Far2Casual** [comment]
Bon ben voilà, je pense que la boucle est bouclée, j'ai couvert je pense à peu près tous les cas que j'ai trouvés, tout est factorisé et rendu générique, le système en place permettra d'intégrer les boutons facilement à de futures commandes.
A moins que tu aies d'autres idées, je pense qu'on peut fermer cette issue obèse qui m'aura occupé quelques mois 😉

**Comment by Ulty** [comment]
Merci pour cet énorme boulot ! Je n'aurais jamais eu le temps de faire tout ça en plus du reste !
