### ISSUE TITLE
Attaques dans liste d'actions par défaut cassées

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#54]
Depuis hier, les attaques automatiquement reprises dans la liste d'actions du joueur ne fonctionnent plus.

Exemple sur ma partie : 
Le joueur Siegfried n'a pas de listes d'actions explicite. Il dispose de plusieurs Ability faisant appel à la macro Attaque dans sa feuille de persos. La première est simple : #Attaque 1 --percant. Voici le résultat dans le chat de !cof-liste-ations :
https://imgur.com/MWnz8d5

Problème : le lien derrière le bouton est : https://app.roll20.net/editor/!cof-lancer-sort%20--lanceur%20-M5TTli3OTVQD1nbHJVd%200%20Attaque%201%20--percant ce qui est évidemment incorrect

**Comment by Ulty** [comment]
Voilà qui est étonnant. Je n'observe pas ça sur mes parties.

De quel lien derrière le bouton parles-tu ?

**Comment by Far2Casual** [comment]
Dans l'image, le lien derrière le bouton #1.ArcLong (visible si tu hover au dessus du bouton). Il fait !cof-lancer-sort au lieu de !cof-attaque.

Je précise aussi que le bouton de Macro, lui, fonctionne. C'est le lien envoyé dans le chat suite à !cof-liste-actions qui est incorrect. Je suis en train de regarder pourquoi, mais je ne vois pas encore.

**Comment by Ulty** [comment]
J'aurais besoin d'en savoir plus. À quoi ressemble ton ability `#Actions#` ? Si il faut !cof-lancer-sort, ça signifie qu'il n'a pas trouvé de commande API au début de ton ability.

**Comment by Far2Casual** [comment]
Le perso n'a pas d'ability #Actions#.
J'ai supprimé et refait les Ability, je n'ai remis que l'Arc long pour l'instant. Ca donne ceci : 
https://imgur.com/fZ6ofk6

**Comment by Ulty** [comment]
Si je ne me trompe pas (l'image n'est pas très nette), tu as des noms d'ability avec des espaces, ce qui n'est pas supporté par Roll20. D'ailleurs si tu tapes une espace dans le champ name, il est automatiquement remplacé par un tiret.

**Comment by Far2Casual** [comment]
L'image est dégueu même je ne sais pas ce que Snippet Tool fait.

Non je n'ai qu'une Ability nommée #1.ArcLong. Ce que tu vois en dessous est le code de l'ability, qui est comme tu le vois une bête attaque.

Cette ability fonctionne ; si je la mets en tant que Token Action, et que j'utilise le bouton #1.ArcLong qui apparaît quand je sélectionne le token, l'attaque se passe sans problème.

Par contre si en sélectionnant le token je fais !cof-action, alors le lien généré dans la liste des actions dans le chat ne fonctionne pas.

**Comment by Ulty** [comment]
Alors ça pourrait être le # au début du nom de l'ability qui n'est pas bien interprété par le script ? Je vais tester ça.

**Comment by Ulty** [comment]
Non, ça marche chez moi avec une ability qui s'appelle #1.Attaque

**Comment by Ulty** [comment]
Ou alors, le nom de ton personnage est peut-être en cause, avec ses quotes au milieu ?

**Comment by Far2Casual** [comment]
Premier élément : tout le setup fonctionnait bien jusqu'à hier soir.
J'ai essayé : 
- de rajouter un #Actions# où je ne reprends que l'Ability Arc Long, même effet.
- Renommer #1.ArcLong en "ArcLong", même effet
- J'ai essayé avec un autre personnage nommé juste Arlyndor (sans espace sans rien), même effet.

En fait ce bug survient sur absolument tous les persos, PJ & PNJ. Aucun bouton de la liste d'Actions lié à une attaque ne fonctionne, par contre les autres actions (style le sort Agrandissement) fonctionne correctement.

**Comment by Far2Casual** [comment]
Je tiens une piste : si dans l'Ability, au lieu de mettre : 
`#Attaque 1 --percant`

Je mets : 
`!cof-attack @{selected|token_id} @{target|token_id}`

La ça fonctionne à nouveau.

**Comment by Ulty** [comment]
Et ta macro, elle aurait changé ?

**Comment by Far2Casual** [comment]
Non, c'est la macro par défaut, elle contient juste : 
!cof-attack @{selected|token_id} @{target|token_id}

**Comment by Ulty** [comment]
C'est très intriguant. Ça le fait aussi sur une nouvelle partie ? Si tu veux, je peux aller voir sur ta partie ?

**Comment by Far2Casual** [comment]
J'ai deux autres parties avec le script et tout, et c'est particulièrement intrigant en effet car je n'ai le problème que sur celle-là. 

Voici pour rejoindre la partie : https://app.roll20.net/join/6401154/u0KnQw

**Comment by Ulty** [comment]
J'essaie mes parties, aucun soucis nulle part.

**Comment by Ulty** [comment]
Si tu peux me mettre MJ, je pourrais regarder ce qu'il se passe dans le script

**Comment by Far2Casual** [comment]
Done. En effet ce n'est pas une problème général mais c'est spécifique à cette partie.

**Comment by Ulty** [comment]
En fait, tu as une macro avec un nom vide, dans cette partie
Et du coup elle est utilisée à la place de Attaque. Je vais regarder comment renforcer un peu le code à ce niveau.

**Comment by Ulty** [comment]
C'est mon expression régulière qui foire si le nom de la macro est vide.

**Comment by Ulty** [comment]
C'est réparé.

**Comment by Far2Casual** [comment]
Bah merde alors, bien vu Ulty, et merci ! 👍
