### ISSUE TITLE
Consommables

### ISSUE THREAD

**Issue by waibcam** [Ulty/COFantasy#6]
Salut !

Je commence a utiliser les consommables. C'est super ce truc.

Par contre, j'ai rencontré un bug avec l'ajout de parchemins pour les commandes : 

- !cof-attack @{selected|token_id} @{target|token_id} 9 --fx beam-fire --feu --sortilege --enflamme
- !cof-lancer-sort 0 lance un sort de mirage pendant [[1d6+@{selected|INT}]] minutes

En fait les commandes fonctionnent mais elles semblent générer une erreur qui empêche le nombre de consommable d'être diminué.

En image : https://imgur.com/a/4B7AK

Voilà, rien de grave mais si tu peux le corriger à l'occasion, ça serait cool.
A +

**Comment by waibcam** [comment]
OOPS !

je viens de voir dans la doc : Pour l'instant, seules les commandes !cof-effet-temp, !cof-effet-combat, !cof-effet, !cof-enduire-poison et !cof-soin diminuent correctement le nombre de consommables.

Désolé :s

**Comment by Ulty** [comment]
Je vois ce que c'est. Je n'ai pas encore ajouté l'option pour toutes les actions !cof possibles, et en particulier pas pour les attaques. Je fais ça dès que j'ai le temps, ça devrait être facile.

Sinon, pour les consommables, je réfléchis encore à une façon de donner les consommables entre joueurs et aussi pour le MJ de donner plus facilement des consommables aux joueurs. Si tu as des idées d'interface...

**Comment by waibcam** [comment]
Ah super ! Merci encore :)

**Donner un consommable entre joueurs :**
Si on peut modifier les attributs via le scripts, je verrai bien un truc dans le style :

On définie un paramètre "echange" pour commande _!cof-consommables --echange_ qui, visuellement fait exactement la même chose : montre la liste des consommable du joueur.
Sauf qu'en cliquant sur le consommable, ça nous demande le @{target|token_id} vers qui on veut donner le consommable (1 par 1). On clique sur le token de notre ami et ca lui ajoute (incrémente s'il est déjà présent dans sa liste) la valeur du consommable ainsi que la commande à utiliser.
Et bien sûr, on diminue de 1 pour le joueur qui échange.

Aussi, ça afficherait un petit message : XXXXXX vient de donner 1 x YYYYYYY à ZZZZZZZ

**Pour le MJ**
C'est plus délicat. Mais on pourrait imaginer que le MJ se crée un perso "MJ" avec tout les consommables possible dans les attributs (en tout cas, tout ceux qu'il veut gérer) et fasse la même procédure que les joueurs (il fera pop son token MJ sur la page et l’enlèvera ensuite)
Toutefois, il faudrait absolument limiter le clic de l'échange au possesseur du token (car ce n'est pas le cas pour _!cof-consommables_, ce qui est normal... même si on pourrait limiter aussi à la consommation une fois que l'échange sera possible).

T'en penses quoi ?

**Comment by Ulty** [comment]
Pour ce qui est de donner un consommable, j'avais effectivement cette idée en tête, mais avec 2 sujets de réflexions encore :
-  Il y a des cas (comme le parchemin de flèche de feu) où simplement copier l'attribut ne suffit pas. Comment y remédier ou au moins le détecter ? Quel message envoyer ?
-  J'aimerais limiter le nombre de boutons associé aux tokens. Ça grossit très très vite avec le niveau (d'où l'utilisation des boutons dans le chat pour la chance et de plus en plus de choses). Donc peut-être mettre à la fois l'utilisation et la possibilité de donner depuis le menu de !cof-consommables, mais il faudrait que ce ne soit pas trop fouillis...

Pour ce qui est du côté MJ, j'aime bien ta solution. On fait juste un PNJ marchant, et hop, c'est bon. Il faudrait juste peut-être lui donner un nom particulier pour adapter les messages, et qu'il ait un stock infini. L'autre solution serait d'utiliser une note, et rajouter une fonction !cof, mais ça rajouterait un bouton. Et il faut bien sûr trouver une solution au problème des parchemins qui utilisent une attaque.

**Comment by Ulty** [comment]
Au fait, pour le parchemin avec 

`!cof-lancer-sort 0 lance un sort de mirage pendant [[1d6+@{selected|INT}]] minutes`

tu peux simplement utiliser 

`lance un sort de mirage pendant [[1d6+@{selected|INT}]] minutes`

**Comment by Ulty** [comment]
En réponse à 

> Toutefois, il faudrait absolument limiter le clic de l'échange au possesseur du token (car ce n'est pas le cas pour !cof-consommables, ce qui est normal... même si on pourrait limiter aussi à la consommation une fois que l'échange sera possible).

En fait, le menu de `!cof-consommable`  est chuchoté au joueur, donc visible de lui seul, ce qui fait que seul lui peut l'utiliser. J'ai fait la même chose pour `!cof-statut` qui est maintenant visible du joueur seul. Il faudra peut-être que je rajoute ça à la doc.

**Comment by waibcam** [comment]
> Il y a des cas (comme le parchemin de flèche de feu) où simplement copier l'attribut ne suffit pas. Comment y remédier ou au moins le détecter ? Quel message envoyer ?

Ne pourrait-on pas améliorer la fonction !cof-attack qui prendrait en 3ième paramètre un truc du genre : 
#[Hache à 2 mains, @{selected|ATKCAC}, 20, 1D8+@{selected|FOR}]
Si possible, c'est nickel je trouve.

**Comment by waibcam** [comment]
> J'aimerais limiter le nombre de boutons associé aux tokens. Ça grossit très très vite avec le niveau (d'où l'utilisation des boutons dans le chat pour la chance et de plus en plus de choses). Donc peut-être mettre à la fois l'utilisation et la possibilité de donner depuis le menu de !cof-consommables, mais il faudrait que ce ne soit pas trop fouillis...

J'ai désormais réglé la question en regroupant les bouton par type d'action : 
- Attaque
- Sort
- Spécial
- etc.

Par exemple, voici la macro du bouton _Attaque_ de mon guerrier : 
```
#Attaque ?{Choisissez votre arme|
EpéeLongue, 1 --tranchant|
Epée Courte en Fer Froid, 3 --tranchant|
Hache à 2 mains, 5 --tranchant
} ?{Y consacrer le tour entier ?|
Non,''|
Oui,--imparable --plus 1D6
}
```
Ça permet de limiter les boutons mais ça fait un menu supplémentaire pour le joueur. Aussi, le joueur a une moins bonne visibilité de ses capacités sur les boutons Token Actions.
Mais bon, je trouve qu'au vu de ce qu'apporte le script, c'est pas très cher payé quand même. 

Du coup, pour les consommables, on pourrait avoir une Macro _Consommables_  qui ferait : 
```
!cof-consommables ?{Choisissez|
Utiliser un consommable,|
Echanger un consommable, --echange
}
```

**Comment by waibcam** [comment]
> tu peux simplement utiliser
> 
> `lance un sort de mirage pendant [[1d6+@{selected|INT}]] minutes`

Ah mais bien sûr ! LOL ! C'est tellement évident, j'ai honte. Merci :)

**Comment by waibcam** [comment]
> En fait, le menu de !cof-consommable est chuchoté au joueur, donc visible de lui seul, ce qui fait que seul lui peut l'utiliser. J'ai fait la même chose pour !cof-statut qui est maintenant visible du joueur seul. Il faudra peut-être que je rajoute ça à la doc.

Ah bah c'est parfait alors !

**Comment by Ulty** [comment]
Pour l'amélioration de `!cof-attack`, c'est une bonne piste, mais ça va me demander du boulot. 

Pour l'utilisation des menus déroulants, je le fais aussi, mais plus pour les capacités. J'ai l'impression qu'il vaut mieux ne pas trop en abuser, et ça peut être un peu délicat à écrire et à débugger, à cause des caractères à échapper, entre autres.  J'ai en tête de faire par exemple un menu de livre de sort, ou une commande de menu générique pour gérer ça. À voir si c'est vraiment plus pratique.

Pour le problèmes des consommables, je ne sais pas encore trop si c'est plus pratique pour le joueur d'avoir un menu déroulant suivi d'une liste dans laquelle cliquer, ou bien directement une liste avec le choix parmi 2 boutons pour chaque consommable.

Une autre piste intéressante pour diminuer le nombre de boutons de token, c'est d'aller directement lire ou même modifier les abilities des personnages. On peut même changer les abilities de token action à non token action.

**Comment by Ulty** [comment]
Bravo pour ta solution. Il manque juste la documentation, maintenant :)

**Comment by waibcam** [comment]
Merci :-) Oui, je fais ça là !

**Comment by waibcam** [comment]
@Ulty J'ai commencé l’implémentation de l'échange. Je devrais pouvoir te montrer ça demain.
Tu me diras si ça te va ou pas.

**Comment by Ulty** [comment]
Super que tu t'y mettes ! Bon courage !

**Comment by waibcam** [comment]
Voilà : https://github.com/Ulty/COFantasy/pull/18

**Comment by waibcam** [comment]
Nouvelles modifications : https://github.com/Ulty/COFantasy/pull/19
