### ISSUE TITLE
Retirer (mort) si !cof-soin réussi sur un perso à 0 PV

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#62]
Salut Ulty, je remarque dans mes parties que si si tu fais !cof-soin sur un perso mort (0 PV + état mort), il ne retire pas automatiquement l'état mort sur le personnage.

C'est par design pour une raison que je ne comprends pas, où je peux rajouter cela ?

**Comment by Ulty** [comment]
Oui, c'est par design. En fait, il faudrait sûrement un second état, car 'mort', pour le moment, peut signifier mort (et seule une résurrection peut changer cet état), soit pour un PJ inconscient, si ça ne fait pas trop longtemps, et dans ce cas un soin peut enlever l'état.

Bref, en l'état actuel, on laisse le MJ décider si un soin ramène à la vie ou pas, selon la fraîcheur du cadavre.

**Comment by Far2Casual** [comment]
Ok ça me va, j'y touche pas ;)
