### ISSUE TITLE
!cof-jet

### ISSUE THREAD

**Issue by waibcam** [Ulty/COFantasy#7]
Salut :-)

Est-ce que tu peux faire en sorte que la fonction !cof-jet prenne un argument "bonus" (et même nom) dans lequel on mettrai, par exemple, 1 ou -2.

L'idée est de pouvoir, par exemple, faire un test de discrétion (DEX) et d'ajouter au jet de dé,  un bonus lié à une compétence passive de mon personnage : 
Exemple : Un Halfelin à naturellement +2 aux tests de discrétion (DEX) mais pas pour un test d'esquive (DEX) ou d'escalade (DEX)

Idéalement, j'aimerai pouvoir faire une macro "Test Discrétion" : 
`!cof-jet DEX --bonus 2 --nom Discrétion`
ou
`!cof-jet DEX 10 --bonus 2 --nom Discrétion`
Cette macro renverrait la même chose que maintenant mais en précisant, dans la FramedDisplay, le bonus/malus s'il est présent : "Jet de Discrétion (+2)"
Si le nom n'est pas précisé, c'est la fonction _caracOfMod_ qui s'en charge.

C'est faisable ?

**Comment by Ulty** [comment]
J'utilise déjà des attributs `perception` ou `vigilance` pour les jets de surprise. On pourrait peut-être se contenter du nom et aller chercher la valeur de l'attribut ? Ou même chercher dans une table selon les rangs dans des voies ?

**Comment by Ulty** [comment]
C'est fait. Dis-moi si ça convient.

**Comment by waibcam** [comment]
C'est parfait 👍 

Merci beaucoup !
