### ISSUE TITLE
Support des casques

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#76]
Techniquement, je sais que le casque est supporté via la RD vs critique, mais ne pourrait-on pas aussi rajouter ça dans la feuille de perso et le gérer comme les armures et boucliers, y compris avec la partie Malus aux tests de Perception ?

**Comment by Ulty** [comment]
Oui, tu as raison. Je rajouterai ça sur la fiche. À terme, le but est d'avoir un système avec de l'équipement sur une base comme celle de la fiche CoC. Tu devrais y jeter un coup d'oeil (à partir de mercredi, je pense), il y a des idées intéressantes.

**Comment by Ulty** [comment]
Support des casques effectif, maintenant.
