### ISSUE TITLE
Consommables !cof-lancer-sort

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#82]
Ulty, je voudrais faire en sorte qu'on puisse faire des consommables "lancer sort" pour les parchemins de sorts qui ne nécessitent pas de support particulier du script (Détection de la Magie, Mirage, etc). Pour ça j'aimerais que les consommables avec !cof-lancer-sort puisse faire diminuer le nombre de consommables comme les autres commandes.

En fait, je l'ai fait, mais j'aimerais revamp la syntaxe de cof-lancer-sorts pour qu'elle soit un peu plus "standard". En clair, changer la syntaxe de la commande vers : 
!cof-lancer-sort TEXTE --mana COUT_EN_MANA --decrAttribute ATTRIBUT_DOSE
Et le script diminue la mana si nécessaire, la dose si nécessaire, puis whisper le texte.

C'est légèrement non rétro-compatible, c'est pour ça que je te pose la question, mais ça me paraît plus robuste que la syntaxe actuelle. OK pour toi ?

**Comment by Ulty** [comment]
Effectivement, ça semble une bonne idée. Il faut juste ne plus permettre de ` --` dans le message du texte, ce qui semble raisonnable. Il faudra aussi penser à enlever `!cof-lancer-sort` de la liste des exceptions dans la fonction `bouton`, de façon à pouvoir préciser qui lance le sort (avec un `--lanceur` ajouté automatiquement). Et bien sûr faire une mise à jour vers une vesion 2.05, pas si évidente à faire : il faut regarder les abilities et les attributs de consommables.

D'ailleurs, une chose à faire pour les mises à jour serait de regarder l'attribut script_version quand on ouvre ou ajoute une fiche, histoire de faire les mises à jour pour cette fiche, si par exemple elle vient d'une autre partie avec le transmogrifier ou bien si elle est importée avec !co-import.

**Comment by Far2Casual** [comment]
Pour l'instant j'avoue je l'ai fait en mode lazy, sans la migration. Mais tu as raison, je vais essayer de la faire, même si elle est hard.

Je comprends pas trop la remarque sur la fonction bouton, justement la fonction rajoute automatiquement un --lanceur si nécessaire, c'est très pratique.

Pour le deuxième paragraphe, ça me semble out-of-scope ici, mais pourquoi pas dans une autre issue ;)

**Comment by Ulty** [comment]
Il y a vraiment un traitement particulier, à la fois dans `bouton` et dans la fonction `lancerSort` elle-même pour le traitement du `--lanceur`. Ce serait mieux si `!cof-lancer-sort` était toujours suivi du message, puis des options commençant par ` --`, comme ça on peut faire plein de chose, comme désigner une cible, faire un fx sur cette cible, faire un son, avoir des limites par jour ou par combat, etc.

**Comment by Far2Casual** [comment]
Hé bien, je pense que je vais juste standardiser la commande complètement. Plutôt que de dupliquer du code inutile, je vais utiliser parseOptions qui implémente déjà tout correctement : 
--mana pour la mana
--decrAttribute et --lanceur sont générés tout seul par bouton() et gérés par parseOptions
--message permet déjà de mettre un message, option que je vais rendre obligatoire dans ce cas-ci

avec l'utilisation de limiteRessources qui implémente aussi déjà tout correctement.
