### ISSUE TITLE
Guérison (Prêtre, voie des soins 4)

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#89]
Un manque évident de support par le script, et tellement populaire/fréquent/utile qu'à mon avis il est urgent de l'implémenter. Je compte faire une nouvelle commande spéciale "cof-guerison" pour ce sort, car l'intégrer à cof-soins me semble inutilement compliqué.

Des suggestions sur les choses que le script pourrait soigner "automatiquement" ? Guérison affecte particulièrement les poisons, maladies, et affaiblissements de caractéristiques. J'ai déjà identifié :
- dotgen(x)
- putrefaction
- saignementsSang

Tu en vois d'autres ?

**Comment by Ulty** [comment]
La partie faire regagner les points de vie devrait être assez facile, mais la raison pour laquelle je n'avais pas directement implémenté cette capacité, c'est l'identification des effets affectés par la guérison du prêtre. 

Par exemple, je ne mettrais pas `saignementsSang`, qui n'est pas une maladie ou un poison, mais un sort actif sur une cible. Pareil pour `putréfaction.` `dotGen` pose problème, car on ne sait pas si c'est employé pour un poison ou tout autre chose. D'ailleurs il n'y a aucun poison ou maladie proposés dans les règles pour lesquels on emploirait dotGen , car ils ne font pas de dégâts par tour.

**Comment by Far2Casual** [comment]
J'ai relu, j'ai rerelu, et au final je me range à ton interprétation. Donc finalement, Guérison _pour le script_ ne fait rien d'autre que de mettre les PV de la cible au max alors. Raison de plus pour le rajouter vite fait alors.

Et ne pas l'inclure dans !cof-soin, c'est surtout parce que le design de cof-soin inclut de l'asynchrone pour les jets et tout le toutim ; dans ce cas-ci, on peut faire plus simple (et donc plus efficace) en réinitialisant simplement la barre de la cible.

**Comment by Ulty** [comment]
En revanche, on pourrait enlever l'état blessé, peut-être, non ?

**Comment by Ulty** [comment]
Merci pour l'implémentation. Tant qu'on n'a pas implémenté des états pour le poison, la maladie ou les diminutions de caracs, je pense qu'on peut fermer cette issue.

**Comment by Bleuzaille** [comment]
Merci @Far2Casual  j'en avais besoin !
C'est une excellente initiative ;-)
