### ISSUE TITLE
Table de trésors

### ISSUE THREAD

**Issue by Far2Casual** [Ulty/COFantasy#94]
J'ai vu que le script commençait à jouer avec les `rollabletable`. Sache que j'ai implémenté en RecursiveTable l'entièreté de la table des trésors (livre de règles p. 197 à 205).

Tu serais intéressé à ce que j'intègre tout cela dans le script ? Deux remarques : 
1. C'est évidemment basé sur l'utilisation du script RecursiveTable
2. Il y a vraiment une chiée de tables à importer (j'en ai 20+). Plutôt que de toutes les inclure à la mano dans le script, dans ce cas-ci je suggérerais d'utiliser le script d'import/export de tables.

**Comment by Ulty** [comment]
Du coup, je me demande si ça a vraiment besoin d'être intégré au script ?

**Comment by Far2Casual** [comment]
Pas con. Ben écoute je vais proposer ça de mon côté alors :sweat_smile:
